
package com.badlogic.gdx.utils;

import static com.badlogic.gdx.Input.Keys.*;

/** This test makes sure that no legacy keycodes were lost during possible Input.java changes/refactorization.
 * @author vaxquis */
public class InputKeycodeTest {
	public int[] keycodes = new int[] {
		ANY_KEY, UNKNOWN,

		SOFT_LEFT, SOFT_RIGHT, HOME, BACK, CALL, ENDCALL,

		NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,

		STAR, POUND,

		DPAD_UP, DPAD_DOWN, DPAD_LEFT, DPAD_RIGHT, DPAD_CENTER,

		UP, DOWN, LEFT, RIGHT, CENTER,

		VOLUME_UP, VOLUME_DOWN, POWER, CAMERA, CLEAR,

		A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,

		COMMA, PERIOD, ALT_LEFT, ALT_RIGHT, SHIFT_LEFT, SHIFT_RIGHT, TAB, SPACE,
		SYM,
		EXPLORER,
		ENVELOPE,
		ENTER,
		DEL, // i.e. backspace, as per doc
		BACKSPACE, GRAVE, MINUS, EQUALS, LEFT_BRACKET, RIGHT_BRACKET, BACKSLASH, SEMICOLON, APOSTROPHE, SLASH, AT, NUM,
		HEADSETHOOK, FOCUS, PLUS, MENU, NOTIFICATION, SEARCH, MEDIA_PLAY_PAUSE, MEDIA_STOP, MEDIA_NEXT, MEDIA_PREVIOUS,
		MEDIA_REWIND, MEDIA_FAST_FORWARD, MUTE, PAGE_UP, PAGE_DOWN, PICTSYMBOLS, SWITCH_CHARSET,

		BUTTON_A, BUTTON_B, BUTTON_C, BUTTON_X, BUTTON_Y, BUTTON_Z, BUTTON_L1, BUTTON_R1, BUTTON_L2, BUTTON_R2,
		BUTTON_THUMBL,
		BUTTON_THUMBR,
		BUTTON_START,
		BUTTON_SELECT,
		BUTTON_MODE,
		BUTTON_CIRCLE, // duplicate of F12, see below
		// ESCAPE=111;
		FORWARD_DEL, // "real" delete
		CTRL_LEFT, CTRL_RIGHT, CAPS_LOCK, SCROLL_LOCK, META_LEFT, META_RIGHT, FUNCTION, SYSRQ, BREAK, MOVE_HOME,
		MOVE_END,
		// INSERT=124;
		FORWARD,
		MEDIA_PLAY,
		MEDIA_PAUSE,
		MEDIA_CLOSE,
		// MEDIA_EJECT=129;
		// MEDIA_RECORD=130;
		CONTROL_LEFT, CONTROL_RIGHT, ESCAPE, END, INSERT,

		NUM_LOCK, NUMPAD_0, NUMPAD_1, NUMPAD_2, NUMPAD_3, NUMPAD_4, NUMPAD_5, NUMPAD_6, NUMPAD_7, NUMPAD_8, NUMPAD_9,
		NUMPAD_DIVIDE, NUMPAD_MULTIPLY, NUMPAD_SUBTRACT, NUMPAD_ADD, NUMPAD_DOT, NUMPAD_COMMA, NUMPAD_ENTER, NUMPAD_EQUALS,
		NUMPAD_LEFT_PAREN, NUMPAD_RIGHT_PAREN,

		// mostly duplicates below
		META_ALT_LEFT_ON, META_ALT_ON, META_ALT_RIGHT_ON, META_SHIFT_LEFT_ON, META_SHIFT_ON, META_SHIFT_RIGHT_ON, META_SYM_ON,

		// BACKTICK,
		// TILDE,
		// UNDERSCORE,
		// DOT,
		// BREAK,
		// PIPE,
		// EXCLAMATION,
		// QUESTIONMARK,
		// ` | VK_BACKTICK
		// ~ | VK_TILDE
		// : | VK_COLON
		// _ | VK_UNDERSCORE
		// . | VK_DOT
		// (break) | VK_BREAK
		// | | VK_PIPE
		// ! | VK_EXCLAMATION
		// ? | VK_QUESTION
		COLON,

		F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
	};

	public void testKeycodes () {
		for (int i : keycodes) {
			System.out.println(i);
		}
	}
}
