/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.inversedynamics;

public final class JointType {
  public final static int FIXED = 0;
  public final static int REVOLUTE = FIXED + 1;
  public final static int PRISMATIC = REVOLUTE + 1;
  public final static int FLOATING = PRISMATIC + 1;
}

