#This is an image built from Dockerfile in devspaces folder
FROM devspaces/libgdx

LABEL description="This file generates a docker image containing everything needed to build LibGDX project"

WORKDIR /data

CMD tail -f /dev/null