name: Bug Report
description: Report a bug

body:
    - type: markdown
      attributes:
          value: |
              ## First of all
              1. Please search for [existing issues](https://github.com/libgdx/libgdx/issues?q=is%3Aissue) about this problem first.

    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: A clear description of what the bug is. Include screenshots if applicable.
          placeholder: Bug description
      

    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction
          description: Steps to reproduce the behavior.
          placeholder: |
              Even if you think your issue is trivial to reproduce, please supply a [SSCCE](https://sscce.org/) that demonstrates your issue. This saves time on our end, and makes it much more likely that your issue will be fixed.
              You can find barebones templates [here](https://libgdx.com/wiki/articles/getting-help)

    - type: input
      id: version
      attributes:
          label: version
          description: Version of libGDX and/or relevant dependencies
          placeholder: |
               Please provide the version(s) affected

    - type: textarea
      id: logs
      attributes:
          label: Stack trace
          render: shell
        
    - type: checkboxes
      id: affected_platforms
      attributes:
          label: "Affected platforms"
          description: "Select all platforms where the issue occurs."
          options:
           - label: "Android"
           - label: "iOS"
           - label: "HTML/GWT"
           - label: "Windows"
           - label: "Linux"
           - label: "macOS"
