name: Feature Request
description: Request a new feature or enhancement
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Please make sure this feature request hasn't been already submitted by someone by looking through other [open/closed issues](https://github.com/libgdx/libgdx/issues?q=is%3Aissue)

    - type: textarea
      id: description
      attributes:
          label: Description
          description: Give us a brief description of the feature or enhancement you would like
      validations:
          required: true

    - type: textarea
      id: additional-information
      attributes:
          label: Additional Information
          description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc
