/*DO NOT EDIT THIS FILE - it is machine generated*/

package com.badlogic.gdx.backends.iosrobovm.custom;

/*<imports>*/
import org.robovm.objc.*;
import org.robovm.objc.annotation.*;
import org.robovm.rt.bro.annotation.*;
import org.robovm.rt.bro.ptr.*;
import org.robovm.apple.foundation.*;

/*</imports>*/
/*<javadoc>*/
/** DO NOT EDIT THIS FILE - it is machine generated
 * @since Available in iOS 2.0 and later.
 * @deprecated Deprecated in iOS 5.0. */
@Deprecated
/* </javadoc> */
/* <annotations> */
@Library("UIKit")
@NativeClass
public class /* </visibility> */
/* <name> */
UIAcceleration extends /* </name> */
/* <extends> */
	NSObject {

	/* </extends> */
	/* <implements> */
	/* </implements> */
	/** DO NOT EDIT THIS FILE - it is machine generated */
	public static class UIAccelerationPtr extends Ptr<UIAcceleration, UIAccelerationPtr> {
	}

	/* </ptr> */
	/* <bind> */
	static {
		ObjCRuntime.bind(UIAcceleration.class);
	}

	/* </bind> */
	/* <constants> */
	/* </constants> */
	/* <constructors> */
	public UIAcceleration () {
	}

	protected UIAcceleration (SkipInit skipInit) {
		super(skipInit);
	}

	/* </constructors> */
	/* <properties> */
	@Property(selector = "timestamp")
	public native double getTimestamp ();

	@Property(selector = "x")
	public native double getX ();

	@Property(selector = "y")
	public native double getY ();

	@Property(selector = "z")
	public native double getZ ();
	/* </properties> */
	/* <members> */
	/* </members> */
	/* <methods> */
	/* </methods> */
}
