
DISABLE_NIO_BUFFER_TYPEMAP(unsigned char);
DISABLE_NIO_BUFFER_TYPEMAP(short);
DISABLE_NIO_BUFFER_TYPEMAP(unsigned short);
DISABLE_NIO_BUFFER_TYPEMAP(int);
DISABLE_NIO_BUFFER_TYPEMAP(unsigned int);
DISABLE_NIO_BUFFER_TYPEMAP(long);
DISABLE_NIO_BUFFER_TYPEMAP(unsigned long);
DISABLE_NIO_BUFFER_TYPEMAP(float);
DISABLE_NIO_BUFFER_TYPEMAP(double);
DISABLE_NIO_BUFFER_TYPEMAP(btScalar);