/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_physics_tokamak_Simulator */

#ifndef _Included_com_badlogic_gdx_physics_tokamak_Simulator
#define _Included_com_badlogic_gdx_physics_tokamak_Simulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    createSimulator
 * Signature: (IIIIIIIIIIIIFFF)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_createSimulator
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    disposeJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_disposeJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    createRigidBodyJni
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_createRigidBodyJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    createRigidParticleJni
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_createRigidParticleJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    createAnimatedBodyJni
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_createAnimatedBodyJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    freeRigidBodyJni
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_freeRigidBodyJni
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    freeAnimatedBodyJni
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_freeAnimatedBodyJni
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    getCollisionTableJNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_getCollisionTableJNI
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    setMaterialJni
 * Signature: (JIFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_setMaterialJni
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    getMaterialJni
 * Signature: (JI[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_getMaterialJni
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    advanceJni
 * Signature: (JFI)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_advanceJni__JFI
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    advanceJni
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_advanceJni__JFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    createJointJni
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_createJointJni__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    createJointJni
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_createJointJni__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    createJointAnimatedBodyJni
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_createJointAnimatedBodyJni
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    freeJointJni
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_freeJointJni
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    getGravityJni
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_getGravityJni
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    setGravityJni
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_setGravityJni
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_badlogic_gdx_physics_tokamak_Simulator
 * Method:    getMemoryAllocatedJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_physics_tokamak_Simulator_getMemoryAllocatedJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
