/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.linearmath;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class GrahamVector3 extends btVector3 {
	private long swigCPtr;
	
	protected GrahamVector3(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, LinearMathJNI.GrahamVector3_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	/** Construct a new GrahamVector3, normally you should not need this constructor it's intended for low-level usage. */
	public GrahamVector3(long cPtr, boolean cMemoryOwn) {
		this("GrahamVector3", cPtr, cMemoryOwn);
		construct();
	}
	
	@Override
	protected void reset(long cPtr, boolean cMemoryOwn) {
		if (!destroyed)
			destroy();
		super.reset(LinearMathJNI.GrahamVector3_SWIGUpcast(swigCPtr = cPtr), cMemoryOwn);
	}
	
	public static long getCPtr(GrahamVector3 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				LinearMathJNI.delete_GrahamVector3(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public GrahamVector3(Vector3 org, int orgIndex) {
    this(LinearMathJNI.new_GrahamVector3(org, orgIndex), true);
  }

  public void setAngle(float value) {
    LinearMathJNI.GrahamVector3_angle_set(swigCPtr, this, value);
  }

  public float getAngle() {
    return LinearMathJNI.GrahamVector3_angle_get(swigCPtr, this);
  }

  public void setOrgIndex(int value) {
    LinearMathJNI.GrahamVector3_orgIndex_set(swigCPtr, this, value);
  }

  public int getOrgIndex() {
    return LinearMathJNI.GrahamVector3_orgIndex_get(swigCPtr, this);
  }

}
