/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_graphics_g3d_loaders_md5_MD5Jni */

#ifndef _Included_com_badlogic_gdx_graphics_g3d_loaders_md5_MD5Jni
#define _Included_com_badlogic_gdx_graphics_g3d_loaders_md5_MD5Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_graphics_g3d_loaders_md5_MD5Jni
 * Method:    calculateVertices
 * Signature: ([F[F[F[FIII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_graphics_g3d_loaders_md5_MD5Jni_calculateVertices
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     com_badlogic_gdx_graphics_g3d_loaders_md5_MD5Jni
 * Method:    calculateVerticesN
 * Signature: ([F[F[F[S[FIIII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_graphics_g3d_loaders_md5_MD5Jni_calculateVerticesN
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jshortArray, jfloatArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
