#define	glClearIndex(_a0) {(void)(_a0);}
#define	glClearColor(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glIndexMask(_a0) {(void)(_a0);}
#define	glColorMask(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glAlphaFunc(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glBlendFunc(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glLogicOp(_a0) {(void)(_a0);}
#define	glCullFace(_a0) {(void)(_a0);}
#define	glFrontFace(_a0) {(void)(_a0);}
#define	glPointSize(_a0) {(void)(_a0);}
#define	glLineWidth(_a0) {(void)(_a0);}
#define	glLineStipple(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPolygonMode(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPolygonOffset(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPolygonStipple(_a0) {(void)(_a0);}
#define	glGetPolygonStipple(_a0) {(void)(_a0);}
#define	glEdgeFlag(_a0) {(void)(_a0);}
#define	glEdgeFlagv(_a0) {(void)(_a0);}
#define	glScissor(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glClipPlane(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glGetClipPlane(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glDrawBuffer(_a0) {(void)(_a0);}
#define	glReadBuffer(_a0) {(void)(_a0);}
#define	glEnable(_a0) {(void)(_a0);}
#define	glDisable(_a0) {(void)(_a0);}
#define	glEnableClientState(_a0) {(void)(_a0);}
#define	glDisableClientState(_a0) {(void)(_a0);}
#define	glPushAttrib(_a0) {(void)(_a0);}
#define	glPopAttrib() {}
#define	glPushClientAttrib(_a0) {(void)(_a0);}
#define	glPopClientAttrib() {}
#define	glHint(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glClearDepth(_a0) {(void)(_a0);}
#define	glDepthFunc(_a0) {(void)(_a0);}
#define	glDepthMask(_a0) {(void)(_a0);}
#define	glDepthRange(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glClearAccum(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glAccum(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glDeleteLists(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glNewList(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glEndList() {}
#define	glCallList(_a0) {(void)(_a0);}
#define	glCallLists(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glListBase(_a0) {(void)(_a0);}
#define	glBegin(_a0) {(void)(_a0);}
#define	glEnd() {}
#define	glVertex2d(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glVertex2f(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glVertex2i(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glVertex2s(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glVertex3d(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glVertex3f(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glVertex3i(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glVertex3s(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glVertex4d(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glVertex4f(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glVertex4i(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glVertex4s(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glVertex2dv(_a0) {(void)(_a0);}
#define	glVertex2fv(_a0) {(void)(_a0);}
#define	glVertex2iv(_a0) {(void)(_a0);}
#define	glVertex2sv(_a0) {(void)(_a0);}
#define	glVertex3dv(_a0) {(void)(_a0);}
#define	glVertex3fv(_a0) {(void)(_a0);}
#define	glVertex3iv(_a0) {(void)(_a0);}
#define	glVertex3sv(_a0) {(void)(_a0);}
#define	glVertex4dv(_a0) {(void)(_a0);}
#define	glVertex4fv(_a0) {(void)(_a0);}
#define	glVertex4iv(_a0) {(void)(_a0);}
#define	glVertex4sv(_a0) {(void)(_a0);}
#define	glNormal3b(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glNormal3d(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glNormal3f(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glNormal3i(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glNormal3s(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glNormal3bv(_a0) {(void)(_a0);}
#define	glNormal3dv(_a0) {(void)(_a0);}
#define	glNormal3fv(_a0) {(void)(_a0);}
#define	glNormal3iv(_a0) {(void)(_a0);}
#define	glNormal3sv(_a0) {(void)(_a0);}
#define	glIndexd(_a0) {(void)(_a0);}
#define	glIndexf(_a0) {(void)(_a0);}
#define	glIndexi(_a0) {(void)(_a0);}
#define	glIndexs(_a0) {(void)(_a0);}
#define	glIndexub(_a0) {(void)(_a0);}
#define	glIndexdv(_a0) {(void)(_a0);}
#define	glIndexfv(_a0) {(void)(_a0);}
#define	glIndexiv(_a0) {(void)(_a0);}
#define	glIndexsv(_a0) {(void)(_a0);}
#define	glIndexubv(_a0) {(void)(_a0);}
#define	glColor3b(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColor3d(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColor3f(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColor3i(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColor3s(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColor3ub(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColor3ui(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColor3us(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColor4b(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glColor4d(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glColor4f(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glColor4i(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glColor4s(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glColor4ub(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glColor4ui(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glColor4us(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glColor3bv(_a0) {(void)(_a0);}
#define	glColor3dv(_a0) {(void)(_a0);}
#define	glColor3fv(_a0) {(void)(_a0);}
#define	glColor3iv(_a0) {(void)(_a0);}
#define	glColor3sv(_a0) {(void)(_a0);}
#define	glColor3ubv(_a0) {(void)(_a0);}
#define	glColor3uiv(_a0) {(void)(_a0);}
#define	glColor3usv(_a0) {(void)(_a0);}
#define	glColor4bv(_a0) {(void)(_a0);}
#define	glColor4dv(_a0) {(void)(_a0);}
#define	glColor4fv(_a0) {(void)(_a0);}
#define	glColor4iv(_a0) {(void)(_a0);}
#define	glColor4sv(_a0) {(void)(_a0);}
#define	glColor4ubv(_a0) {(void)(_a0);}
#define	glColor4uiv(_a0) {(void)(_a0);}
#define	glColor4usv(_a0) {(void)(_a0);}
#define	glTexCoord1d(_a0) {(void)(_a0);}
#define	glTexCoord1f(_a0) {(void)(_a0);}
#define	glTexCoord1i(_a0) {(void)(_a0);}
#define	glTexCoord1s(_a0) {(void)(_a0);}
#define	glTexCoord2d(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glTexCoord2f(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glTexCoord2i(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glTexCoord2s(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glTexCoord3d(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexCoord3f(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexCoord3i(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexCoord3s(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexCoord4d(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glTexCoord4f(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glTexCoord4i(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glTexCoord4s(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glTexCoord1dv(_a0) {(void)(_a0);}
#define	glTexCoord1fv(_a0) {(void)(_a0);}
#define	glTexCoord1iv(_a0) {(void)(_a0);}
#define	glTexCoord1sv(_a0) {(void)(_a0);}
#define	glTexCoord2dv(_a0) {(void)(_a0);}
#define	glTexCoord2fv(_a0) {(void)(_a0);}
#define	glTexCoord2iv(_a0) {(void)(_a0);}
#define	glTexCoord2sv(_a0) {(void)(_a0);}
#define	glTexCoord3dv(_a0) {(void)(_a0);}
#define	glTexCoord3fv(_a0) {(void)(_a0);}
#define	glTexCoord3iv(_a0) {(void)(_a0);}
#define	glTexCoord3sv(_a0) {(void)(_a0);}
#define	glTexCoord4dv(_a0) {(void)(_a0);}
#define	glTexCoord4fv(_a0) {(void)(_a0);}
#define	glTexCoord4iv(_a0) {(void)(_a0);}
#define	glTexCoord4sv(_a0) {(void)(_a0);}
#define	glRasterPos2d(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glRasterPos2f(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glRasterPos2i(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glRasterPos2s(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glRasterPos3d(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glRasterPos3f(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glRasterPos3i(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glRasterPos3s(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glRasterPos4d(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glRasterPos4f(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glRasterPos4i(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glRasterPos4s(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glRasterPos2dv(_a0) {(void)(_a0);}
#define	glRasterPos2fv(_a0) {(void)(_a0);}
#define	glRasterPos2iv(_a0) {(void)(_a0);}
#define	glRasterPos2sv(_a0) {(void)(_a0);}
#define	glRasterPos3dv(_a0) {(void)(_a0);}
#define	glRasterPos3fv(_a0) {(void)(_a0);}
#define	glRasterPos3iv(_a0) {(void)(_a0);}
#define	glRasterPos3sv(_a0) {(void)(_a0);}
#define	glRasterPos4dv(_a0) {(void)(_a0);}
#define	glRasterPos4fv(_a0) {(void)(_a0);}
#define	glRasterPos4iv(_a0) {(void)(_a0);}
#define	glRasterPos4sv(_a0) {(void)(_a0);}
#define	glRectd(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glRectf(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glRecti(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glRects(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glRectdv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glRectfv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glRectiv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glRectsv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glVertexPointer(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glNormalPointer(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColorPointer(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glIndexPointer(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexCoordPointer(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glEdgeFlagPointer(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glGetPointerv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glArrayElement(_a0) {(void)(_a0);}
#define	glDrawArrays(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glDrawElements(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glInterleavedArrays(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glShadeModel(_a0) {(void)(_a0);}
#define	glLightf(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glLighti(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glLightfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glLightiv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetLightfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetLightiv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glLightModelf(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glLightModeli(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glLightModelfv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glLightModeliv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMaterialf(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMateriali(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMaterialfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMaterialiv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetMaterialfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetMaterialiv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColorMaterial(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPixelZoom(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPixelStoref(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPixelStorei(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPixelTransferf(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPixelTransferi(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPixelMapfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glPixelMapuiv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glPixelMapusv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetPixelMapfv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glGetPixelMapuiv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glGetPixelMapusv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glBitmap(_a0,_a1,_a2,_a3,_a4,_a5,_a6) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);}
#define	glReadPixels(_a0,_a1,_a2,_a3,_a4,_a5,_a6) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);}
#define	glDrawPixels(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glCopyPixels(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glStencilFunc(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glStencilMask(_a0) {(void)(_a0);}
#define	glStencilOp(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glClearStencil(_a0) {(void)(_a0);}
#define	glTexGend(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexGenf(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexGeni(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexGendv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexGenfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexGeniv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetTexGendv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetTexGenfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetTexGeniv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexEnvf(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexEnvi(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexEnvfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexEnviv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetTexEnvfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetTexEnviv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexParameterf(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexParameteri(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexParameterfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexParameteriv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetTexParameterfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetTexParameteriv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetTexLevelParameterfv(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glGetTexLevelParameteriv(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glTexImage1D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);}
#define	glTexImage2D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);}
#define	glGetTexImage(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glGenTextures(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glDeleteTextures(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glBindTexture(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glPrioritizeTextures(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glTexSubImage1D(_a0,_a1,_a2,_a3,_a4,_a5,_a6) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);}
#define	glTexSubImage2D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);}
#define	glCopyTexImage1D(_a0,_a1,_a2,_a3,_a4,_a5,_a6) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);}
#define	glCopyTexImage2D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);}
#define	glCopyTexSubImage1D(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glCopyTexSubImage2D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);}
#define	glMap1d(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glMap1f(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glMap2d(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8,_a9) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);(void)(_a9);}
#define	glMap2f(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8,_a9) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);(void)(_a9);}
#define	glGetMapdv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetMapfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetMapiv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glEvalCoord1d(_a0) {(void)(_a0);}
#define	glEvalCoord1f(_a0) {(void)(_a0);}
#define	glEvalCoord1dv(_a0) {(void)(_a0);}
#define	glEvalCoord1fv(_a0) {(void)(_a0);}
#define	glEvalCoord2d(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glEvalCoord2f(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glEvalCoord2dv(_a0) {(void)(_a0);}
#define	glEvalCoord2fv(_a0) {(void)(_a0);}
#define	glMapGrid1d(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMapGrid1f(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMapGrid2d(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glMapGrid2f(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glEvalPoint1(_a0) {(void)(_a0);}
#define	glEvalPoint2(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glEvalMesh1(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glEvalMesh2(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glFogf(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glFogi(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glFogfv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glFogiv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glFeedbackBuffer(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glPassThrough(_a0) {(void)(_a0);}
#define	glSelectBuffer(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glInitNames() {}
#define	glLoadName(_a0) {(void)(_a0);}
#define	glPushName(_a0) {(void)(_a0);}
#define	glPopName() {}
#define	glDrawRangeElements(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glTexImage3D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8,_a9) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);(void)(_a9);}
#define	glTexSubImage3D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8,_a9,_a10) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);(void)(_a9);(void)(_a10);}
#define	glCopyTexSubImage3D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);}
#define	glColorTable(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glColorSubTable(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glColorTableParameteriv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glColorTableParameterfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glCopyColorSubTable(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glCopyColorTable(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glGetColorTable(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glGetColorTableParameterfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetColorTableParameteriv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glBlendEquation(_a0) {(void)(_a0);}
#define	glBlendColor(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glHistogram(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glResetHistogram(_a0) {(void)(_a0);}
#define	glGetHistogram(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glGetHistogramParameterfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetHistogramParameteriv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMinmax(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glResetMinmax(_a0) {(void)(_a0);}
#define	glGetMinmax(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glGetMinmaxParameterfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetMinmaxParameteriv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glConvolutionFilter1D(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glConvolutionFilter2D(_a0,_a1,_a2,_a3,_a4,_a5,_a6) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);}
#define	glConvolutionParameterf(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glConvolutionParameterfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glConvolutionParameteri(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glConvolutionParameteriv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glCopyConvolutionFilter1D(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glCopyConvolutionFilter2D(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glGetConvolutionFilter(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glGetConvolutionParameterfv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glGetConvolutionParameteriv(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glSeparableFilter2D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);}
#define	glGetSeparableFilter(_a0,_a1,_a2,_a3,_a4,_a5) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);}
#define	glActiveTexture(_a0) {(void)(_a0);}
#define	glClientActiveTexture(_a0) {(void)(_a0);}
#define	glCompressedTexImage1D(_a0,_a1,_a2,_a3,_a4,_a5,_a6) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);}
#define	glCompressedTexImage2D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);}
#define	glCompressedTexImage3D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);}
#define	glCompressedTexSubImage1D(_a0,_a1,_a2,_a3,_a4,_a5,_a6) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);}
#define	glCompressedTexSubImage2D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);}
#define	glCompressedTexSubImage3D(_a0,_a1,_a2,_a3,_a4,_a5,_a6,_a7,_a8,_a9,_a10) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);(void)(_a5);(void)(_a6);(void)(_a7);(void)(_a8);(void)(_a9);(void)(_a10);}
#define	glGetCompressedTexImage(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord1d(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1dv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1f(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1fv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1i(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1iv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1s(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1sv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord2d(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord2dv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord2f(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord2fv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord2i(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord2iv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord2s(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord2sv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord3d(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glMultiTexCoord3dv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord3f(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glMultiTexCoord3fv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord3i(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glMultiTexCoord3iv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord3s(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glMultiTexCoord3sv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord4d(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glMultiTexCoord4dv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord4f(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glMultiTexCoord4fv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord4i(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glMultiTexCoord4iv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord4s(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glMultiTexCoord4sv(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glLoadTransposeMatrixd(_a0) {(void)(_a0);}
#define	glLoadTransposeMatrixf(_a0) {(void)(_a0);}
#define	glMultTransposeMatrixd(_a0) {(void)(_a0);}
#define	glMultTransposeMatrixf(_a0) {(void)(_a0);}
#define	glSampleCoverage(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glActiveTextureARB(_a0) {(void)(_a0);}
#define	glClientActiveTextureARB(_a0) {(void)(_a0);}
#define	glMultiTexCoord1dARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1dvARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1fARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1fvARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1iARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1ivARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1sARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord1svARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord2dARB(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord2dvARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord2fARB(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord2fvARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord2iARB(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord2ivARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord2sARB(_a0,_a1,_a2) {(void)(_a0);(void)(_a1);(void)(_a2);}
#define	glMultiTexCoord2svARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord3dARB(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glMultiTexCoord3dvARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord3fARB(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glMultiTexCoord3fvARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord3iARB(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glMultiTexCoord3ivARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord3sARB(_a0,_a1,_a2,_a3) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);}
#define	glMultiTexCoord3svARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord4dARB(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glMultiTexCoord4dvARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord4fARB(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glMultiTexCoord4fvARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord4iARB(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glMultiTexCoord4ivARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
#define	glMultiTexCoord4sARB(_a0,_a1,_a2,_a3,_a4) {(void)(_a0);(void)(_a1);(void)(_a2);(void)(_a3);(void)(_a4);}
#define	glMultiTexCoord4svARB(_a0,_a1) {(void)(_a0);(void)(_a1);}
