#ifndef	EGL_TOKENS_H
#define	EGL_TOKENS_H

#define	EGL_TOKEN_glClearIndex            	0x0
#define	EGL_TOKEN_glClearColor            	0x1
#define	EGL_TOKEN_glClear                 	0x2
#define	EGL_TOKEN_glIndexMask             	0x3
#define	EGL_TOKEN_glColorMask             	0x4
#define	EGL_TOKEN_glAlphaFunc             	0x5
#define	EGL_TOKEN_glBlendFunc             	0x6
#define	EGL_TOKEN_glLogicOp               	0x7
#define	EGL_TOKEN_glCullFace              	0x8
#define	EGL_TOKEN_glFrontFace             	0x9
#define	EGL_TOKEN_glPointSize             	0xa
#define	EGL_TOKEN_glLineWidth             	0xb
#define	EGL_TOKEN_glLineStipple           	0xc
#define	EGL_TOKEN_glPolygonMode           	0xd
#define	EGL_TOKEN_glPolygonOffset         	0xe
#define	EGL_TOKEN_glPolygonStipple        	0xf
#define	EGL_TOKEN_glGetPolygonStipple     	0x10
#define	EGL_TOKEN_glEdgeFlag              	0x11
#define	EGL_TOKEN_glEdgeFlagv             	0x12
#define	EGL_TOKEN_glScissor               	0x13
#define	EGL_TOKEN_glClipPlane             	0x14
#define	EGL_TOKEN_glGetClipPlane          	0x15
#define	EGL_TOKEN_glDrawBuffer            	0x16
#define	EGL_TOKEN_glReadBuffer            	0x17
#define	EGL_TOKEN_glEnable                	0x18
#define	EGL_TOKEN_glDisable               	0x19
#define	EGL_TOKEN_glIsEnabled             	0x1a
#define	EGL_TOKEN_glEnableClientState     	0x1b
#define	EGL_TOKEN_glDisableClientState    	0x1c
#define	EGL_TOKEN_glGetBooleanv           	0x1d
#define	EGL_TOKEN_glGetDoublev            	0x1e
#define	EGL_TOKEN_glGetFloatv             	0x1f
#define	EGL_TOKEN_glGetIntegerv           	0x20
#define	EGL_TOKEN_glPushAttrib            	0x21
#define	EGL_TOKEN_glPopAttrib             	0x22
#define	EGL_TOKEN_glPushClientAttrib      	0x23
#define	EGL_TOKEN_glPopClientAttrib       	0x24
#define	EGL_TOKEN_glRenderMode            	0x25
#define	EGL_TOKEN_glGetError              	0x26
#define	EGL_TOKEN_glGetString             	0x27
#define	EGL_TOKEN_glFinish                	0x28
#define	EGL_TOKEN_glFlush                 	0x29
#define	EGL_TOKEN_glHint                  	0x2a
#define	EGL_TOKEN_glClearDepth            	0x2b
#define	EGL_TOKEN_glDepthFunc             	0x2c
#define	EGL_TOKEN_glDepthMask             	0x2d
#define	EGL_TOKEN_glDepthRange            	0x2e
#define	EGL_TOKEN_glClearAccum            	0x2f
#define	EGL_TOKEN_glAccum                 	0x30
#define	EGL_TOKEN_glMatrixMode            	0x31
#define	EGL_TOKEN_glOrtho                 	0x32
#define	EGL_TOKEN_glFrustum               	0x33
#define	EGL_TOKEN_glViewport              	0x34
#define	EGL_TOKEN_glPushMatrix            	0x35
#define	EGL_TOKEN_glPopMatrix             	0x36
#define	EGL_TOKEN_glLoadIdentity          	0x37
#define	EGL_TOKEN_glLoadMatrixd           	0x38
#define	EGL_TOKEN_glLoadMatrixf           	0x39
#define	EGL_TOKEN_glMultMatrixd           	0x3a
#define	EGL_TOKEN_glMultMatrixf           	0x3b
#define	EGL_TOKEN_glRotated               	0x3c
#define	EGL_TOKEN_glRotatef               	0x3d
#define	EGL_TOKEN_glScaled                	0x3e
#define	EGL_TOKEN_glScalef                	0x3f
#define	EGL_TOKEN_glTranslated            	0x40
#define	EGL_TOKEN_glTranslatef            	0x41
#define	EGL_TOKEN_glIsList                	0x42
#define	EGL_TOKEN_glDeleteLists           	0x43
#define	EGL_TOKEN_glGenLists              	0x44
#define	EGL_TOKEN_glNewList               	0x45
#define	EGL_TOKEN_glEndList               	0x46
#define	EGL_TOKEN_glCallList              	0x47
#define	EGL_TOKEN_glCallLists             	0x48
#define	EGL_TOKEN_glListBase              	0x49
#define	EGL_TOKEN_glBegin                 	0x4a
#define	EGL_TOKEN_glEnd                   	0x4b
#define	EGL_TOKEN_glVertex2d              	0x4c
#define	EGL_TOKEN_glVertex2f              	0x4d
#define	EGL_TOKEN_glVertex2i              	0x4e
#define	EGL_TOKEN_glVertex2s              	0x4f
#define	EGL_TOKEN_glVertex3d              	0x50
#define	EGL_TOKEN_glVertex3f              	0x51
#define	EGL_TOKEN_glVertex3i              	0x52
#define	EGL_TOKEN_glVertex3s              	0x53
#define	EGL_TOKEN_glVertex4d              	0x54
#define	EGL_TOKEN_glVertex4f              	0x55
#define	EGL_TOKEN_glVertex4i              	0x56
#define	EGL_TOKEN_glVertex4s              	0x57
#define	EGL_TOKEN_glVertex2dv             	0x58
#define	EGL_TOKEN_glVertex2fv             	0x59
#define	EGL_TOKEN_glVertex2iv             	0x5a
#define	EGL_TOKEN_glVertex2sv             	0x5b
#define	EGL_TOKEN_glVertex3dv             	0x5c
#define	EGL_TOKEN_glVertex3fv             	0x5d
#define	EGL_TOKEN_glVertex3iv             	0x5e
#define	EGL_TOKEN_glVertex3sv             	0x5f
#define	EGL_TOKEN_glVertex4dv             	0x60
#define	EGL_TOKEN_glVertex4fv             	0x61
#define	EGL_TOKEN_glVertex4iv             	0x62
#define	EGL_TOKEN_glVertex4sv             	0x63
#define	EGL_TOKEN_glNormal3b              	0x64
#define	EGL_TOKEN_glNormal3d              	0x65
#define	EGL_TOKEN_glNormal3f              	0x66
#define	EGL_TOKEN_glNormal3i              	0x67
#define	EGL_TOKEN_glNormal3s              	0x68
#define	EGL_TOKEN_glNormal3bv             	0x69
#define	EGL_TOKEN_glNormal3dv             	0x6a
#define	EGL_TOKEN_glNormal3fv             	0x6b
#define	EGL_TOKEN_glNormal3iv             	0x6c
#define	EGL_TOKEN_glNormal3sv             	0x6d
#define	EGL_TOKEN_glIndexd                	0x6e
#define	EGL_TOKEN_glIndexf                	0x6f
#define	EGL_TOKEN_glIndexi                	0x70
#define	EGL_TOKEN_glIndexs                	0x71
#define	EGL_TOKEN_glIndexub               	0x72
#define	EGL_TOKEN_glIndexdv               	0x73
#define	EGL_TOKEN_glIndexfv               	0x74
#define	EGL_TOKEN_glIndexiv               	0x75
#define	EGL_TOKEN_glIndexsv               	0x76
#define	EGL_TOKEN_glIndexubv              	0x77
#define	EGL_TOKEN_glColor3b               	0x78
#define	EGL_TOKEN_glColor3d               	0x79
#define	EGL_TOKEN_glColor3f               	0x7a
#define	EGL_TOKEN_glColor3i               	0x7b
#define	EGL_TOKEN_glColor3s               	0x7c
#define	EGL_TOKEN_glColor3ub              	0x7d
#define	EGL_TOKEN_glColor3ui              	0x7e
#define	EGL_TOKEN_glColor3us              	0x7f
#define	EGL_TOKEN_glColor4b               	0x80
#define	EGL_TOKEN_glColor4d               	0x81
#define	EGL_TOKEN_glColor4f               	0x82
#define	EGL_TOKEN_glColor4i               	0x83
#define	EGL_TOKEN_glColor4s               	0x84
#define	EGL_TOKEN_glColor4ub              	0x85
#define	EGL_TOKEN_glColor4ui              	0x86
#define	EGL_TOKEN_glColor4us              	0x87
#define	EGL_TOKEN_glColor3bv              	0x88
#define	EGL_TOKEN_glColor3dv              	0x89
#define	EGL_TOKEN_glColor3fv              	0x8a
#define	EGL_TOKEN_glColor3iv              	0x8b
#define	EGL_TOKEN_glColor3sv              	0x8c
#define	EGL_TOKEN_glColor3ubv             	0x8d
#define	EGL_TOKEN_glColor3uiv             	0x8e
#define	EGL_TOKEN_glColor3usv             	0x8f
#define	EGL_TOKEN_glColor4bv              	0x90
#define	EGL_TOKEN_glColor4dv              	0x91
#define	EGL_TOKEN_glColor4fv              	0x92
#define	EGL_TOKEN_glColor4iv              	0x93
#define	EGL_TOKEN_glColor4sv              	0x94
#define	EGL_TOKEN_glColor4ubv             	0x95
#define	EGL_TOKEN_glColor4uiv             	0x96
#define	EGL_TOKEN_glColor4usv             	0x97
#define	EGL_TOKEN_glTexCoord1d            	0x98
#define	EGL_TOKEN_glTexCoord1f            	0x99
#define	EGL_TOKEN_glTexCoord1i            	0x9a
#define	EGL_TOKEN_glTexCoord1s            	0x9b
#define	EGL_TOKEN_glTexCoord2d            	0x9c
#define	EGL_TOKEN_glTexCoord2f            	0x9d
#define	EGL_TOKEN_glTexCoord2i            	0x9e
#define	EGL_TOKEN_glTexCoord2s            	0x9f
#define	EGL_TOKEN_glTexCoord3d            	0xa0
#define	EGL_TOKEN_glTexCoord3f            	0xa1
#define	EGL_TOKEN_glTexCoord3i            	0xa2
#define	EGL_TOKEN_glTexCoord3s            	0xa3
#define	EGL_TOKEN_glTexCoord4d            	0xa4
#define	EGL_TOKEN_glTexCoord4f            	0xa5
#define	EGL_TOKEN_glTexCoord4i            	0xa6
#define	EGL_TOKEN_glTexCoord4s            	0xa7
#define	EGL_TOKEN_glTexCoord1dv           	0xa8
#define	EGL_TOKEN_glTexCoord1fv           	0xa9
#define	EGL_TOKEN_glTexCoord1iv           	0xaa
#define	EGL_TOKEN_glTexCoord1sv           	0xab
#define	EGL_TOKEN_glTexCoord2dv           	0xac
#define	EGL_TOKEN_glTexCoord2fv           	0xad
#define	EGL_TOKEN_glTexCoord2iv           	0xae
#define	EGL_TOKEN_glTexCoord2sv           	0xaf
#define	EGL_TOKEN_glTexCoord3dv           	0xb0
#define	EGL_TOKEN_glTexCoord3fv           	0xb1
#define	EGL_TOKEN_glTexCoord3iv           	0xb2
#define	EGL_TOKEN_glTexCoord3sv           	0xb3
#define	EGL_TOKEN_glTexCoord4dv           	0xb4
#define	EGL_TOKEN_glTexCoord4fv           	0xb5
#define	EGL_TOKEN_glTexCoord4iv           	0xb6
#define	EGL_TOKEN_glTexCoord4sv           	0xb7
#define	EGL_TOKEN_glRasterPos2d           	0xb8
#define	EGL_TOKEN_glRasterPos2f           	0xb9
#define	EGL_TOKEN_glRasterPos2i           	0xba
#define	EGL_TOKEN_glRasterPos2s           	0xbb
#define	EGL_TOKEN_glRasterPos3d           	0xbc
#define	EGL_TOKEN_glRasterPos3f           	0xbd
#define	EGL_TOKEN_glRasterPos3i           	0xbe
#define	EGL_TOKEN_glRasterPos3s           	0xbf
#define	EGL_TOKEN_glRasterPos4d           	0xc0
#define	EGL_TOKEN_glRasterPos4f           	0xc1
#define	EGL_TOKEN_glRasterPos4i           	0xc2
#define	EGL_TOKEN_glRasterPos4s           	0xc3
#define	EGL_TOKEN_glRasterPos2dv          	0xc4
#define	EGL_TOKEN_glRasterPos2fv          	0xc5
#define	EGL_TOKEN_glRasterPos2iv          	0xc6
#define	EGL_TOKEN_glRasterPos2sv          	0xc7
#define	EGL_TOKEN_glRasterPos3dv          	0xc8
#define	EGL_TOKEN_glRasterPos3fv          	0xc9
#define	EGL_TOKEN_glRasterPos3iv          	0xca
#define	EGL_TOKEN_glRasterPos3sv          	0xcb
#define	EGL_TOKEN_glRasterPos4dv          	0xcc
#define	EGL_TOKEN_glRasterPos4fv          	0xcd
#define	EGL_TOKEN_glRasterPos4iv          	0xce
#define	EGL_TOKEN_glRasterPos4sv          	0xcf
#define	EGL_TOKEN_glRectd                 	0xd0
#define	EGL_TOKEN_glRectf                 	0xd1
#define	EGL_TOKEN_glRecti                 	0xd2
#define	EGL_TOKEN_glRects                 	0xd3
#define	EGL_TOKEN_glRectdv                	0xd4
#define	EGL_TOKEN_glRectfv                	0xd5
#define	EGL_TOKEN_glRectiv                	0xd6
#define	EGL_TOKEN_glRectsv                	0xd7
#define	EGL_TOKEN_glVertexPointer         	0xd8
#define	EGL_TOKEN_glNormalPointer         	0xd9
#define	EGL_TOKEN_glColorPointer          	0xda
#define	EGL_TOKEN_glIndexPointer          	0xdb
#define	EGL_TOKEN_glTexCoordPointer       	0xdc
#define	EGL_TOKEN_glEdgeFlagPointer       	0xdd
#define	EGL_TOKEN_glGetPointerv           	0xde
#define	EGL_TOKEN_glArrayElement          	0xdf
#define	EGL_TOKEN_glDrawArrays            	0xe0
#define	EGL_TOKEN_glDrawElements          	0xe1
#define	EGL_TOKEN_glInterleavedArrays     	0xe2
#define	EGL_TOKEN_glShadeModel            	0xe3
#define	EGL_TOKEN_glLightf                	0xe4
#define	EGL_TOKEN_glLighti                	0xe5
#define	EGL_TOKEN_glLightfv               	0xe6
#define	EGL_TOKEN_glLightiv               	0xe7
#define	EGL_TOKEN_glGetLightfv            	0xe8
#define	EGL_TOKEN_glGetLightiv            	0xe9
#define	EGL_TOKEN_glLightModelf           	0xea
#define	EGL_TOKEN_glLightModeli           	0xeb
#define	EGL_TOKEN_glLightModelfv          	0xec
#define	EGL_TOKEN_glLightModeliv          	0xed
#define	EGL_TOKEN_glMaterialf             	0xee
#define	EGL_TOKEN_glMateriali             	0xef
#define	EGL_TOKEN_glMaterialfv            	0xf0
#define	EGL_TOKEN_glMaterialiv            	0xf1
#define	EGL_TOKEN_glGetMaterialfv         	0xf2
#define	EGL_TOKEN_glGetMaterialiv         	0xf3
#define	EGL_TOKEN_glColorMaterial         	0xf4
#define	EGL_TOKEN_glPixelZoom             	0xf5
#define	EGL_TOKEN_glPixelStoref           	0xf6
#define	EGL_TOKEN_glPixelStorei           	0xf7
#define	EGL_TOKEN_glPixelTransferf        	0xf8
#define	EGL_TOKEN_glPixelTransferi        	0xf9
#define	EGL_TOKEN_glPixelMapfv            	0xfa
#define	EGL_TOKEN_glPixelMapuiv           	0xfb
#define	EGL_TOKEN_glPixelMapusv           	0xfc
#define	EGL_TOKEN_glGetPixelMapfv         	0xfd
#define	EGL_TOKEN_glGetPixelMapuiv        	0xfe
#define	EGL_TOKEN_glGetPixelMapusv        	0xff
#define	EGL_TOKEN_glBitmap                	0x100
#define	EGL_TOKEN_glReadPixels            	0x101
#define	EGL_TOKEN_glDrawPixels            	0x102
#define	EGL_TOKEN_glCopyPixels            	0x103
#define	EGL_TOKEN_glStencilFunc           	0x104
#define	EGL_TOKEN_glStencilMask           	0x105
#define	EGL_TOKEN_glStencilOp             	0x106
#define	EGL_TOKEN_glClearStencil          	0x107
#define	EGL_TOKEN_glTexGend               	0x108
#define	EGL_TOKEN_glTexGenf               	0x109
#define	EGL_TOKEN_glTexGeni               	0x10a
#define	EGL_TOKEN_glTexGendv              	0x10b
#define	EGL_TOKEN_glTexGenfv              	0x10c
#define	EGL_TOKEN_glTexGeniv              	0x10d
#define	EGL_TOKEN_glGetTexGendv           	0x10e
#define	EGL_TOKEN_glGetTexGenfv           	0x10f
#define	EGL_TOKEN_glGetTexGeniv           	0x110
#define	EGL_TOKEN_glTexEnvf               	0x111
#define	EGL_TOKEN_glTexEnvi               	0x112
#define	EGL_TOKEN_glTexEnvfv              	0x113
#define	EGL_TOKEN_glTexEnviv              	0x114
#define	EGL_TOKEN_glGetTexEnvfv           	0x115
#define	EGL_TOKEN_glGetTexEnviv           	0x116
#define	EGL_TOKEN_glTexParameterf         	0x117
#define	EGL_TOKEN_glTexParameteri         	0x118
#define	EGL_TOKEN_glTexParameterfv        	0x119
#define	EGL_TOKEN_glTexParameteriv        	0x11a
#define	EGL_TOKEN_glGetTexParameterfv     	0x11b
#define	EGL_TOKEN_glGetTexParameteriv     	0x11c
#define	EGL_TOKEN_glGetTexLevelParameterfv	0x11d
#define	EGL_TOKEN_glGetTexLevelParameteriv	0x11e
#define	EGL_TOKEN_glTexImage1D            	0x11f
#define	EGL_TOKEN_glTexImage2D            	0x120
#define	EGL_TOKEN_glGetTexImage           	0x121
#define	EGL_TOKEN_glGenTextures           	0x122
#define	EGL_TOKEN_glDeleteTextures        	0x123
#define	EGL_TOKEN_glBindTexture           	0x124
#define	EGL_TOKEN_glPrioritizeTextures    	0x125
#define	EGL_TOKEN_glAreTexturesResident   	0x126
#define	EGL_TOKEN_glIsTexture             	0x127
#define	EGL_TOKEN_glTexSubImage1D         	0x128
#define	EGL_TOKEN_glTexSubImage2D         	0x129
#define	EGL_TOKEN_glCopyTexImage1D        	0x12a
#define	EGL_TOKEN_glCopyTexImage2D        	0x12b
#define	EGL_TOKEN_glCopyTexSubImage1D     	0x12c
#define	EGL_TOKEN_glCopyTexSubImage2D     	0x12d
#define	EGL_TOKEN_glMap1d                 	0x12e
#define	EGL_TOKEN_glMap1f                 	0x12f
#define	EGL_TOKEN_glMap2d                 	0x130
#define	EGL_TOKEN_glMap2f                 	0x131
#define	EGL_TOKEN_glGetMapdv              	0x132
#define	EGL_TOKEN_glGetMapfv              	0x133
#define	EGL_TOKEN_glGetMapiv              	0x134
#define	EGL_TOKEN_glEvalCoord1d           	0x135
#define	EGL_TOKEN_glEvalCoord1f           	0x136
#define	EGL_TOKEN_glEvalCoord1dv          	0x137
#define	EGL_TOKEN_glEvalCoord1fv          	0x138
#define	EGL_TOKEN_glEvalCoord2d           	0x139
#define	EGL_TOKEN_glEvalCoord2f           	0x13a
#define	EGL_TOKEN_glEvalCoord2dv          	0x13b
#define	EGL_TOKEN_glEvalCoord2fv          	0x13c
#define	EGL_TOKEN_glMapGrid1d             	0x13d
#define	EGL_TOKEN_glMapGrid1f             	0x13e
#define	EGL_TOKEN_glMapGrid2d             	0x13f
#define	EGL_TOKEN_glMapGrid2f             	0x140
#define	EGL_TOKEN_glEvalPoint1            	0x141
#define	EGL_TOKEN_glEvalPoint2            	0x142
#define	EGL_TOKEN_glEvalMesh1             	0x143
#define	EGL_TOKEN_glEvalMesh2             	0x144
#define	EGL_TOKEN_glFogf                  	0x145
#define	EGL_TOKEN_glFogi                  	0x146
#define	EGL_TOKEN_glFogfv                 	0x147
#define	EGL_TOKEN_glFogiv                 	0x148
#define	EGL_TOKEN_glFeedbackBuffer        	0x149
#define	EGL_TOKEN_glPassThrough           	0x14a
#define	EGL_TOKEN_glSelectBuffer          	0x14b
#define	EGL_TOKEN_glInitNames             	0x14c
#define	EGL_TOKEN_glLoadName              	0x14d
#define	EGL_TOKEN_glPushName              	0x14e
#define	EGL_TOKEN_glPopName               	0x14f
#define	EGL_TOKEN_glDrawRangeElements     	0x150
#define	EGL_TOKEN_glTexImage3D            	0x151
#define	EGL_TOKEN_glTexSubImage3D         	0x152
#define	EGL_TOKEN_glCopyTexSubImage3D     	0x153
#define	EGL_TOKEN_glColorTable            	0x154
#define	EGL_TOKEN_glColorSubTable         	0x155
#define	EGL_TOKEN_glColorTableParameteriv 	0x156
#define	EGL_TOKEN_glColorTableParameterfv 	0x157
#define	EGL_TOKEN_glCopyColorSubTable     	0x158
#define	EGL_TOKEN_glCopyColorTable        	0x159
#define	EGL_TOKEN_glGetColorTable         	0x15a
#define	EGL_TOKEN_glGetColorTableParameterfv	0x15b
#define	EGL_TOKEN_glGetColorTableParameteriv	0x15c
#define	EGL_TOKEN_glBlendEquation         	0x15d
#define	EGL_TOKEN_glBlendColor            	0x15e
#define	EGL_TOKEN_glHistogram             	0x15f
#define	EGL_TOKEN_glResetHistogram        	0x160
#define	EGL_TOKEN_glGetHistogram          	0x161
#define	EGL_TOKEN_glGetHistogramParameterfv	0x162
#define	EGL_TOKEN_glGetHistogramParameteriv	0x163
#define	EGL_TOKEN_glMinmax                	0x164
#define	EGL_TOKEN_glResetMinmax           	0x165
#define	EGL_TOKEN_glGetMinmax             	0x166
#define	EGL_TOKEN_glGetMinmaxParameterfv  	0x167
#define	EGL_TOKEN_glGetMinmaxParameteriv  	0x168
#define	EGL_TOKEN_glConvolutionFilter1D   	0x169
#define	EGL_TOKEN_glConvolutionFilter2D   	0x16a
#define	EGL_TOKEN_glConvolutionParameterf 	0x16b
#define	EGL_TOKEN_glConvolutionParameterfv	0x16c
#define	EGL_TOKEN_glConvolutionParameteri 	0x16d
#define	EGL_TOKEN_glConvolutionParameteriv	0x16e
#define	EGL_TOKEN_glCopyConvolutionFilter1D	0x16f
#define	EGL_TOKEN_glCopyConvolutionFilter2D	0x170
#define	EGL_TOKEN_glGetConvolutionFilter  	0x171
#define	EGL_TOKEN_glGetConvolutionParameterfv	0x172
#define	EGL_TOKEN_glGetConvolutionParameteriv	0x173
#define	EGL_TOKEN_glSeparableFilter2D     	0x174
#define	EGL_TOKEN_glGetSeparableFilter    	0x175
#define	EGL_TOKEN_glActiveTexture         	0x176
#define	EGL_TOKEN_glClientActiveTexture   	0x177
#define	EGL_TOKEN_glCompressedTexImage1D  	0x178
#define	EGL_TOKEN_glCompressedTexImage2D  	0x179
#define	EGL_TOKEN_glCompressedTexImage3D  	0x17a
#define	EGL_TOKEN_glCompressedTexSubImage1D	0x17b
#define	EGL_TOKEN_glCompressedTexSubImage2D	0x17c
#define	EGL_TOKEN_glCompressedTexSubImage3D	0x17d
#define	EGL_TOKEN_glGetCompressedTexImage 	0x17e
#define	EGL_TOKEN_glMultiTexCoord1d       	0x17f
#define	EGL_TOKEN_glMultiTexCoord1dv      	0x180
#define	EGL_TOKEN_glMultiTexCoord1f       	0x181
#define	EGL_TOKEN_glMultiTexCoord1fv      	0x182
#define	EGL_TOKEN_glMultiTexCoord1i       	0x183
#define	EGL_TOKEN_glMultiTexCoord1iv      	0x184
#define	EGL_TOKEN_glMultiTexCoord1s       	0x185
#define	EGL_TOKEN_glMultiTexCoord1sv      	0x186
#define	EGL_TOKEN_glMultiTexCoord2d       	0x187
#define	EGL_TOKEN_glMultiTexCoord2dv      	0x188
#define	EGL_TOKEN_glMultiTexCoord2f       	0x189
#define	EGL_TOKEN_glMultiTexCoord2fv      	0x18a
#define	EGL_TOKEN_glMultiTexCoord2i       	0x18b
#define	EGL_TOKEN_glMultiTexCoord2iv      	0x18c
#define	EGL_TOKEN_glMultiTexCoord2s       	0x18d
#define	EGL_TOKEN_glMultiTexCoord2sv      	0x18e
#define	EGL_TOKEN_glMultiTexCoord3d       	0x18f
#define	EGL_TOKEN_glMultiTexCoord3dv      	0x190
#define	EGL_TOKEN_glMultiTexCoord3f       	0x191
#define	EGL_TOKEN_glMultiTexCoord3fv      	0x192
#define	EGL_TOKEN_glMultiTexCoord3i       	0x193
#define	EGL_TOKEN_glMultiTexCoord3iv      	0x194
#define	EGL_TOKEN_glMultiTexCoord3s       	0x195
#define	EGL_TOKEN_glMultiTexCoord3sv      	0x196
#define	EGL_TOKEN_glMultiTexCoord4d       	0x197
#define	EGL_TOKEN_glMultiTexCoord4dv      	0x198
#define	EGL_TOKEN_glMultiTexCoord4f       	0x199
#define	EGL_TOKEN_glMultiTexCoord4fv      	0x19a
#define	EGL_TOKEN_glMultiTexCoord4i       	0x19b
#define	EGL_TOKEN_glMultiTexCoord4iv      	0x19c
#define	EGL_TOKEN_glMultiTexCoord4s       	0x19d
#define	EGL_TOKEN_glMultiTexCoord4sv      	0x19e
#define	EGL_TOKEN_glLoadTransposeMatrixd  	0x19f
#define	EGL_TOKEN_glLoadTransposeMatrixf  	0x1a0
#define	EGL_TOKEN_glMultTransposeMatrixd  	0x1a1
#define	EGL_TOKEN_glMultTransposeMatrixf  	0x1a2
#define	EGL_TOKEN_glSampleCoverage        	0x1a3
#define	EGL_TOKEN_glActiveTextureARB      	0x1a4
#define	EGL_TOKEN_glClientActiveTextureARB	0x1a5
#define	EGL_TOKEN_glMultiTexCoord1dARB    	0x1a6
#define	EGL_TOKEN_glMultiTexCoord1dvARB   	0x1a7
#define	EGL_TOKEN_glMultiTexCoord1fARB    	0x1a8
#define	EGL_TOKEN_glMultiTexCoord1fvARB   	0x1a9
#define	EGL_TOKEN_glMultiTexCoord1iARB    	0x1aa
#define	EGL_TOKEN_glMultiTexCoord1ivARB   	0x1ab
#define	EGL_TOKEN_glMultiTexCoord1sARB    	0x1ac
#define	EGL_TOKEN_glMultiTexCoord1svARB   	0x1ad
#define	EGL_TOKEN_glMultiTexCoord2dARB    	0x1ae
#define	EGL_TOKEN_glMultiTexCoord2dvARB   	0x1af
#define	EGL_TOKEN_glMultiTexCoord2fARB    	0x1b0
#define	EGL_TOKEN_glMultiTexCoord2fvARB   	0x1b1
#define	EGL_TOKEN_glMultiTexCoord2iARB    	0x1b2
#define	EGL_TOKEN_glMultiTexCoord2ivARB   	0x1b3
#define	EGL_TOKEN_glMultiTexCoord2sARB    	0x1b4
#define	EGL_TOKEN_glMultiTexCoord2svARB   	0x1b5
#define	EGL_TOKEN_glMultiTexCoord3dARB    	0x1b6
#define	EGL_TOKEN_glMultiTexCoord3dvARB   	0x1b7
#define	EGL_TOKEN_glMultiTexCoord3fARB    	0x1b8
#define	EGL_TOKEN_glMultiTexCoord3fvARB   	0x1b9
#define	EGL_TOKEN_glMultiTexCoord3iARB    	0x1ba
#define	EGL_TOKEN_glMultiTexCoord3ivARB   	0x1bb
#define	EGL_TOKEN_glMultiTexCoord3sARB    	0x1bc
#define	EGL_TOKEN_glMultiTexCoord3svARB   	0x1bd
#define	EGL_TOKEN_glMultiTexCoord4dARB    	0x1be
#define	EGL_TOKEN_glMultiTexCoord4dvARB   	0x1bf
#define	EGL_TOKEN_glMultiTexCoord4fARB    	0x1c0
#define	EGL_TOKEN_glMultiTexCoord4fvARB   	0x1c1
#define	EGL_TOKEN_glMultiTexCoord4iARB    	0x1c2
#define	EGL_TOKEN_glMultiTexCoord4ivARB   	0x1c3
#define	EGL_TOKEN_glMultiTexCoord4sARB    	0x1c4
#define	EGL_TOKEN_glMultiTexCoord4svARB   	0x1c5

#endif
