LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
 
LOCAL_MODULE    := gdx-glbase
LOCAL_C_INCLUDES := freeimage/Source/LibJXR/common/include/guid/ freeimage/Source freeimage/Source/Metadata freeimage/Source/FreeImageToolkit freeimage/Source/LibJPEG freeimage/Source/LibPNG freeimage/Source/LibTIFF4 freeimage/Source/ZLib freeimage/Source/LibOpenJPEG freeimage/Source/OpenEXR freeimage/Source/OpenEXR/Half freeimage/Source/OpenEXR/Iex freeimage/Source/OpenEXR/IlmImf freeimage/Source/OpenEXR/IlmThread freeimage/Source/OpenEXR/Imath freeimage/Source/LibRawLite freeimage/Source/LibRawLite/dcraw freeimage/Source/LibRawLite/internal freeimage/Source/LibRawLite/libraw freeimage/Source/LibRawLite/src freeimage/Source/LibWebP freeimage/Source/LibJXR freeimage/Source/LibJXR/common/include freeimage/Source/LibJXR/image/sys freeimage/Source/LibJXR/jxrgluelib glbase/inc glbase/src 
 
LOCAL_CFLAGS := $(LOCAL_C_INCLUDES:%=-I%) -O2 -Wall -D__ANDROID__
LOCAL_CPPFLAGS := $(LOCAL_C_INCLUDES:%=-I%) -O2 -Wall -D__ANDROID__ -std=c99 -Wno-error=write-strings -Wno-error=format -ffast-math -funroll-loops -fpic -ffunction-sections -funwind-tables -fno-short-enums -fexceptions -frtti -DBS_ERROR_LOG
LOCAL_LDLIBS := -lm -llog -lGLESv2
LOCAL_ARM_MODE  := arm
 
LOCAL_SRC_FILES := freeimage/Source/DeprecationManager/Deprecated.cpp\
	freeimage/Source/DeprecationManager/DeprecationMgr.cpp\
	freeimage/Source/LibOpenJPEG/mqc.c\
	freeimage/Source/LibOpenJPEG/mct.c\
	freeimage/Source/LibOpenJPEG/dwt.c\
	freeimage/Source/LibOpenJPEG/tcd.c\
	freeimage/Source/LibOpenJPEG/openjpeg.c\
	freeimage/Source/LibOpenJPEG/image.c\
	freeimage/Source/LibOpenJPEG/function_list.c\
	freeimage/Source/LibOpenJPEG/jp2.c\
	freeimage/Source/LibOpenJPEG/event.c\
	freeimage/Source/LibOpenJPEG/raw.c\
	freeimage/Source/LibOpenJPEG/tgt.c\
	freeimage/Source/LibOpenJPEG/invert.c\
	freeimage/Source/LibOpenJPEG/opj_clock.c\
	freeimage/Source/LibOpenJPEG/bio.c\
	freeimage/Source/LibOpenJPEG/t2.c\
	freeimage/Source/LibOpenJPEG/t1.c\
	freeimage/Source/LibOpenJPEG/j2k.c\
	freeimage/Source/LibOpenJPEG/pi.c\
	freeimage/Source/LibOpenJPEG/cio.c\
	freeimage/Source/Metadata/FreeImageTag.cpp\
	freeimage/Source/Metadata/Exif.cpp\
	freeimage/Source/Metadata/IPTC.cpp\
	freeimage/Source/Metadata/FIRational.cpp\
	freeimage/Source/Metadata/TagLib.cpp\
	freeimage/Source/FreeImage/PluginPSD.cpp\
	freeimage/Source/FreeImage/PluginJP2.cpp\
	freeimage/Source/FreeImage/Conversion.cpp\
	freeimage/Source/FreeImage/Plugin.cpp\
	freeimage/Source/FreeImage/ColorLookup.cpp\
	freeimage/Source/FreeImage/ZLibInterface.cpp\
	freeimage/Source/FreeImage/FreeImageC.c\
	freeimage/Source/FreeImage/Conversion24.cpp\
	freeimage/Source/FreeImage/PluginPCX.cpp\
	freeimage/Source/FreeImage/Conversion4.cpp\
	freeimage/Source/FreeImage/WuQuantizer.cpp\
	freeimage/Source/FreeImage/PluginIFF.cpp\
	freeimage/Source/FreeImage/Conversion8.cpp\
	freeimage/Source/FreeImage/PluginJ2K.cpp\
	freeimage/Source/FreeImage/PluginDDS.cpp\
	freeimage/Source/FreeImage/Conversion16_555.cpp\
	freeimage/Source/FreeImage/PluginMNG.cpp\
	freeimage/Source/FreeImage/ConversionRGB16.cpp\
	freeimage/Source/FreeImage/tmoDrago03.cpp\
	freeimage/Source/FreeImage/ConversionFloat.cpp\
	freeimage/Source/FreeImage/BitmapAccess.cpp\
	freeimage/Source/FreeImage/PluginPNG.cpp\
	freeimage/Source/FreeImage/PixelAccess.cpp\
	freeimage/Source/FreeImage/Conversion16_565.cpp\
	freeimage/Source/FreeImage/FreeImageIO.cpp\
	freeimage/Source/FreeImage/tmoColorConvert.cpp\
	freeimage/Source/FreeImage/PluginKOALA.cpp\
	freeimage/Source/FreeImage/PluginXPM.cpp\
	freeimage/Source/FreeImage/PluginPCD.cpp\
	freeimage/Source/FreeImage/tmoReinhard05.cpp\
	freeimage/Source/FreeImage/PluginICO.cpp\
	freeimage/Source/FreeImage/Conversion32.cpp\
	freeimage/Source/FreeImage/ConversionUINT16.cpp\
	freeimage/Source/FreeImage/tmoFattal02.cpp\
	freeimage/Source/FreeImage/MemoryIO.cpp\
	freeimage/Source/FreeImage/PluginSGI.cpp\
	freeimage/Source/FreeImage/PluginXBM.cpp\
	freeimage/Source/FreeImage/PluginEXR.cpp\
	freeimage/Source/FreeImage/MNGHelper.cpp\
	freeimage/Source/FreeImage/ToneMapping.cpp\
	freeimage/Source/FreeImage/ConversionRGBF.cpp\
	freeimage/Source/FreeImage/PluginPFM.cpp\
	freeimage/Source/FreeImage/NNQuantizer.cpp\
	freeimage/Source/FreeImage/PluginGIF.cpp\
	freeimage/Source/FreeImage/ConversionType.cpp\
	freeimage/Source/FreeImage/PSDParser.cpp\
	freeimage/Source/FreeImage/PluginCUT.cpp\
	freeimage/Source/FreeImage/PluginWBMP.cpp\
	freeimage/Source/FreeImage/PluginHDR.cpp\
	freeimage/Source/FreeImage/PluginJPEG.cpp\
	freeimage/Source/FreeImage/PluginBMP.cpp\
	freeimage/Source/FreeImage/PluginTARGA.cpp\
	freeimage/Source/FreeImage/J2KHelper.cpp\
	freeimage/Source/FreeImage/Halftoning.cpp\
	freeimage/Source/FreeImage/PluginRAS.cpp\
	freeimage/Source/FreeImage/GetType.cpp\
	freeimage/Source/FreeImage/PluginJNG.cpp\
	freeimage/Source/FreeImage/CacheFile.cpp\
	freeimage/Source/FreeImage/PluginPNM.cpp\
	freeimage/Source/FreeImage/PluginPICT.cpp\
	freeimage/Source/FreeImage/FreeImage.cpp\
	freeimage/Source/FreeImage/MultiPage.cpp\
	freeimage/Source/LibPNG/pngmem.c\
	freeimage/Source/LibPNG/pngerror.c\
	freeimage/Source/LibPNG/pngwrite.c\
	freeimage/Source/LibPNG/pngread.c\
	freeimage/Source/LibPNG/png.c\
	freeimage/Source/LibPNG/pngwtran.c\
	freeimage/Source/LibPNG/pngrio.c\
	freeimage/Source/LibPNG/pngset.c\
	freeimage/Source/LibPNG/pngtrans.c\
	freeimage/Source/LibPNG/pngpread.c\
	freeimage/Source/LibPNG/pngrutil.c\
	freeimage/Source/LibPNG/pngrtran.c\
	freeimage/Source/LibPNG/pngget.c\
	freeimage/Source/LibPNG/pngwutil.c\
	freeimage/Source/LibPNG/pngwio.c\
	freeimage/Source/FreeImageToolkit/Rescale.cpp\
	freeimage/Source/FreeImageToolkit/ClassicRotate.cpp\
	freeimage/Source/FreeImageToolkit/JPEGTransform.cpp\
	freeimage/Source/FreeImageToolkit/Display.cpp\
	freeimage/Source/FreeImageToolkit/Flip.cpp\
	freeimage/Source/FreeImageToolkit/Channels.cpp\
	freeimage/Source/FreeImageToolkit/Background.cpp\
	freeimage/Source/FreeImageToolkit/Resize.cpp\
	freeimage/Source/FreeImageToolkit/CopyPaste.cpp\
	freeimage/Source/FreeImageToolkit/Colors.cpp\
	freeimage/Source/FreeImageToolkit/MultigridPoissonSolver.cpp\
	freeimage/Source/FreeImageToolkit/BSplineRotate.cpp\
	freeimage/Source/OpenEXR/Imath/ImathRandom.cpp\
	freeimage/Source/OpenEXR/Imath/ImathVec.cpp\
	freeimage/Source/OpenEXR/Imath/ImathFun.cpp\
	freeimage/Source/OpenEXR/Imath/ImathShear.cpp\
	freeimage/Source/OpenEXR/Imath/ImathMatrixAlgo.cpp\
	freeimage/Source/OpenEXR/Imath/ImathColorAlgo.cpp\
	freeimage/Source/OpenEXR/Imath/ImathBox.cpp\
	freeimage/Source/OpenEXR/Iex/IexThrowErrnoExc.cpp\
	freeimage/Source/OpenEXR/Iex/IexBaseExc.cpp\
	freeimage/Source/OpenEXR/IlmThread/IlmThreadPool.cpp\
	freeimage/Source/OpenEXR/IlmThread/IlmThreadSemaphore.cpp\
	freeimage/Source/OpenEXR/IlmThread/IlmThread.cpp\
	freeimage/Source/OpenEXR/IlmThread/IlmThreadMutex.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfIO.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfLut.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfChromaticities.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfLineOrderAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfRgbaFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfFrameBuffer.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfStandardAttributes.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfRationalAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfStringVectorAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTestFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfVersion.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTiledRgbaFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfConvert.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfCompressionAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfMatrixAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfStringAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTimeCode.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTileOffsets.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfKeyCode.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfStdIO.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfHuf.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfPxr24Compressor.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfOpaqueAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfPreviewImage.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfPizCompressor.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfCRgbaFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfMisc.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfRational.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfChannelList.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTiledOutputFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfDoubleAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfB44Compressor.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfIntAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfScanLineInputFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfBoxAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfEnvmap.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfChromaticitiesAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfThreading.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfChannelListAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfRleCompressor.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfHeader.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfKeyCodeAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfInputFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfPreviewImageAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTiledMisc.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfCompressor.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfEnvmapAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfFramesPerSecond.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfZipCompressor.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfWav.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfFloatAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfOutputFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTiledInputFile.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTileDescriptionAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfVecAttribute.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfRgbaYca.cpp\
	freeimage/Source/OpenEXR/IlmImf/ImfTimeCodeAttribute.cpp\
	freeimage/Source/OpenEXR/Half/half.cpp\
	freeimage/Source/ZLib/gzlib.c\
	freeimage/Source/ZLib/crc32.c\
	freeimage/Source/ZLib/compress.c\
	freeimage/Source/ZLib/gzread.c\
	freeimage/Source/ZLib/trees.c\
	freeimage/Source/ZLib/uncompr.c\
	freeimage/Source/ZLib/inffast.c\
	freeimage/Source/ZLib/deflate.c\
	freeimage/Source/ZLib/inflate.c\
	freeimage/Source/ZLib/infback.c\
	freeimage/Source/ZLib/gzclose.c\
	freeimage/Source/ZLib/adler32.c\
	freeimage/Source/ZLib/zutil.c\
	freeimage/Source/ZLib/gzwrite.c\
	freeimage/Source/ZLib/inftrees.c\
	freeimage/Source/LibJPEG/jcmarker.c\
	freeimage/Source/LibJPEG/jfdctflt.c\
	freeimage/Source/LibJPEG/jdatadst.c\
	freeimage/Source/LibJPEG/jdtrans.c\
	freeimage/Source/LibJPEG/jcparam.c\
	freeimage/Source/LibJPEG/jdinput.c\
	freeimage/Source/LibJPEG/jchuff.c\
	freeimage/Source/LibJPEG/jcsample.c\
	freeimage/Source/LibJPEG/transupp.c\
	freeimage/Source/LibJPEG/jaricom.c\
	freeimage/Source/LibJPEG/jdmarker.c\
	freeimage/Source/LibJPEG/jccolor.c\
	freeimage/Source/LibJPEG/jerror.c\
	freeimage/Source/LibJPEG/jdsample.c\
	freeimage/Source/LibJPEG/jcprepct.c\
	freeimage/Source/LibJPEG/jcmainct.c\
	freeimage/Source/LibJPEG/jfdctfst.c\
	freeimage/Source/LibJPEG/jdpostct.c\
	freeimage/Source/LibJPEG/jdmaster.c\
	freeimage/Source/LibJPEG/jctrans.c\
	freeimage/Source/LibJPEG/jcinit.c\
	freeimage/Source/LibJPEG/jdatasrc.c\
	freeimage/Source/LibJPEG/jdhuff.c\
	freeimage/Source/LibJPEG/jutils.c\
	freeimage/Source/LibJPEG/jdarith.c\
	freeimage/Source/LibJPEG/jquant2.c\
	freeimage/Source/LibJPEG/jcapimin.c\
	freeimage/Source/LibJPEG/jquant1.c\
	freeimage/Source/LibJPEG/jfdctint.c\
	freeimage/Source/LibJPEG/jdapimin.c\
	freeimage/Source/LibJPEG/jddctmgr.c\
	freeimage/Source/LibJPEG/jmemmgr.c\
	freeimage/Source/LibJPEG/jidctflt.c\
	freeimage/Source/LibJPEG/jidctfst.c\
	freeimage/Source/LibJPEG/jcarith.c\
	freeimage/Source/LibJPEG/jdapistd.c\
	freeimage/Source/LibJPEG/jdcoefct.c\
	freeimage/Source/LibJPEG/jdmainct.c\
	freeimage/Source/LibJPEG/jidctint.c\
	freeimage/Source/LibJPEG/jcdctmgr.c\
	freeimage/Source/LibJPEG/jdmerge.c\
	freeimage/Source/LibJPEG/jcomapi.c\
	freeimage/Source/LibJPEG/jcmaster.c\
	freeimage/Source/LibJPEG/jdcolor.c\
	freeimage/Source/LibJPEG/jmemnobs.c\
	freeimage/Source/LibJPEG/jcapistd.c\
	freeimage/Source/LibJPEG/jccoefct.c\
	glbase/src/textureLoaderPKM.cpp\
	glbase/src/myUniforms.cpp\
	glbase/src/timer.cpp\
	glbase/src/textureTable.cpp\
	glbase/src/texture.cpp\
	glbase/src/arrayList.cpp\
	glbase/src/binder.cpp\
	glbase/src/etc1_utils.cpp\
	glbase/src/animationPlayer.cpp\
	glbase/src/IrenderQueue.cpp\
	glbase/src/shapeRenderer.cpp\
	glbase/src/textureLoaderFI.cpp\
	glbase/src/animationBbm.cpp\
	glbase/src/textureCube.cpp\
	glbase/src/animationBsBin.cpp\
	glbase/src/fboTable.cpp\
	glbase/src/object.cpp\
	glbase/src/textureLoader.cpp\
	glbase/src/textureLoaderATI.cpp\
	glbase/src/textureLoaderCTES.cpp\
	glbase/src/drawCallsPool.cpp\
	glbase/src/matrix.cpp\
	glbase/src/renderQueue.cpp\
	glbase/src/renderSettings.cpp\
	glbase/src/Iglbase.cpp\
	glbase/src/textureLoaderPVR.cpp\
	glbase/src/Lerp.cpp\
	glbase/src/renderList.cpp\
	glbase/src/json.cpp\
	glbase/src/polygonBuffer.cpp\
	glbase/src/bone.cpp\
	glbase/src/polygonMap.cpp\
	glbase/src/fileUtils.cpp\
	glbase/src/macros.cpp\
	glbase/src/framebuffer.cpp\
	glbase/src/animation.cpp\
	glbase/src/drawCall.cpp\
	glbase/src/textureCompressed.cpp\
	glbase/src/matrixStack.cpp\
	glbase/src/vectors.cpp\
	glbase/src/surface.cpp\
	glbase/src/renderPass.cpp\
	glbase/src/mrf.cpp\
	glbase/src/glbase.cpp\
	glbase/src/vertexBuffer.cpp\
	glbase/src/layer.cpp\
	glbase/src/arrayX.cpp\
	glbase/src/animationTable.cpp\
	glbase/src/mergeGroup.cpp\
	glbase/src/shaderProgram.cpp\
	glbase/src/shaderTable.cpp\
	glbase/src/scene.cpp\
	glbase/src/uniform.cpp\
	glbase/src/textureLoaderPKMBMP.cpp\
	com.btdstudio.glbase.IGLBase.cpp\
	com.btdstudio.glbase.IRenderQueue.cpp\
	com.btdstudio.glbase.IMergeGroup.cpp\
	com.btdstudio.glbase.IAnimationPlayer.cpp\
	com.btdstudio.glbase.Matrix.cpp\
	com.btdstudio.glbase.IObject.cpp\
	com.btdstudio.glbase.ILayer.cpp\
	com.btdstudio.glbase.BasicRenderParameters.cpp\
	com.btdstudio.glbase.RenderParameters.cpp\
	com.btdstudio.glbase.DrawCall.cpp\
	com.btdstudio.glbase.IMrf.cpp\
	com.btdstudio.glbase.IPolygonMap.cpp\
	com.btdstudio.glbase.IRenderPass.cpp\
	com.btdstudio.glbase.ISurface.cpp
 
include $(BUILD_SHARED_LIBRARY)
