/*DO NOT EDIT THIS FILE - it is machine generated*/

package com.badlogic.gdx.backends.iosrobovm;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.graphics.glutils.HdpiMode;
import com.badlogic.gdx.input.NativeInputConfiguration;
import org.robovm.apple.coregraphics.CGPoint;
import org.robovm.apple.coregraphics.CGRect;
import org.robovm.apple.coregraphics.CGSize;
import org.robovm.apple.foundation.*;
import com.badlogic.gdx.backends.iosrobovm.bindings.metalangle.MGLKViewController;
import org.robovm.apple.uikit.*;
import org.robovm.objc.Selector;
import org.robovm.objc.annotation.Method;

/** DO NOT EDIT THIS FILE - it is machine generated */
public class IOSUIViewController extends MGLKViewController {

	final IOSApplication app;

	final IOSGraphics graphics;

	protected IOSUIViewController (IOSApplication app, IOSGraphics graphics) {
		this.app = app;
		this.graphics = graphics;
	}

	@Override
	public void viewWillAppear (boolean animated) {
		super.viewWillAppear(animated);
		// start GLKViewController even though we may only draw a single frame
		// (we may be in non-continuous mode)
		setPaused(false);
		injectKeyboardNotification();
	}

	protected Input.KeyboardHeightObserver observer;

	private boolean softKeyboardShown;

	@Method(selector = "keyboardWillHide")
	public void keyboardWillHide (NSNotification notification) {
		softKeyboardShown = false;
		UIView view = graphics.input.getActiveKeyboardTextField();
		if (view == null) {
			if (observer != null) {
				observer.onKeyboardHide();
				observer.onKeyboardHeightChanged(0);
			}
		} else {
			// On iPad a keyboard can close because it 1. the close button was pressed and 2. a password auto-fill was requested
			// We can differentiate them, if in postRunnable the view is still first responder. If it is -> password auto-fill and we
			// ignore that the keyboard closed
			// If not, dispatch to observer and request close
			Gdx.app.postRunnable( () -> {
				UIView active = graphics.input.getActiveKeyboardTextField();
				if (view != active) {
					// Our field was closed meanwhile (own closeTextInputField / setOnscreenKeyboardVisible(false)).
					// Don't touch `view` — it may be disposed. If it was replaced by a new field, its
					// keyboardWillShow already fired, so swallow the stale hide.
					if (active == null && observer != null) {
						observer.onKeyboardHide();
						observer.onKeyboardHeightChanged(0);
					}
					return;
				}
				if (view.isFirstResponder()) {
					// Editing continues without a docked keyboard: floating/split keyboard, hardware keyboard or a transient
					// hide like the password auto-fill sheet. Don't close, but don't leave the field at its stale position
					moveTextFieldToBottom(true);
					return;
				}
				if (observer != null) {
					observer.onKeyboardHide();
					observer.onKeyboardHeightChanged(0);
				}
				if (graphics.input.isTextInputFieldOpened()) graphics.input.closeTextInputField(false);
			});
		}
	}

	@Method(selector = "keyboardWillShow")
	public void keyboardWillShow (NSNotification notification) {
		softKeyboardShown = true;
		CGRect screenRect = UIScreen.getMainScreen().getBounds();
		double screenHeight = screenRect.getSize().getHeight();
		double heightScale = Gdx.graphics.getHeight() / screenHeight;
		NSDictionary<NSString, ?> userInfo = (NSDictionary<NSString, ?>)notification.getUserInfo();
		CGRect keyboardFrameScreen = ((NSValue)userInfo.get(UIKeyboardAnimation.Keys.FrameEnd())).rectValue();
		UIView textField = graphics.input.getActiveKeyboardTextField();
		if (textField == null || !textField.isFirstResponder() || textField.isHidden()) {
			if (observer != null) {
				int kbHeight = (int)(keyboardFrameScreen.getSize().getHeight() * heightScale);
				observer.onKeyboardShow(kbHeight);
				observer.onKeyboardHeightChanged(kbHeight);
			}
			return;
		}
		// I haven't found any docs on when keyboardWillShow constructs a implicit animation, so iOS 15 should be fine
		if (Foundation.getMajorSystemVersion() <= 15) {
			double duration;
			long curve;
			curve = ((NSNumber)userInfo.get(UIKeyboardAnimation.Keys.AnimationCurve())).longValue();
			duration = ((NSNumber)userInfo.get(UIKeyboardAnimation.Keys.AnimationDuration())).doubleValue();
			UIView.beginAnimations(null, null);
			UIView.setAnimationDurationInSeconds(duration);
			UIView.setAnimationCurve(UIViewAnimationCurve.valueOf(curve));
		}
		UIView accessoryView = textField.getInputAccessoryView();
		if (observer != null) {
			int kbHeight = (int)((keyboardFrameScreen.getSize().getHeight() + textField.getFrame().getSize().getHeight())
				* heightScale);
			if (Foundation.getMajorSystemVersion() >= 26 && accessoryView != null) {
				kbHeight -= (int)(accessoryView.getBounds().getSize().getHeight() * heightScale);
			}
			observer.onKeyboardShow(kbHeight);
			observer.onKeyboardHeightChanged(kbHeight);
		}
		layoutTextFieldAboveKeyboard(textField, keyboardFrameScreen);
		if (Foundation.getMajorSystemVersion() <= 15) {
			UIView.commitAnimations();
		}
	}

	protected void layoutTextFieldAboveKeyboard (UIView textField, CGRect keyboardFrameScreen) {
		NativeInputConfiguration configuration = graphics.input.getNativeInputConfiguration();
		float insetFraction = configuration != null ? configuration.getHorizontalInsetFraction() : 0;
		double fallbackInset = getView().getBounds().getSize().getWidth() * insetFraction;
		UIView accessoryView = textField.getInputAccessoryView();
		CGRect newFrame = textField.getFrame();
		CGRect keyboardFrameInTextField = textField.convertRectToView(keyboardFrameScreen, null);
		double keyboardHeight = keyboardFrameInTextField.getSize().getHeight();
		double specialRightInset = 0;
		if (Foundation.getMajorSystemVersion() >= 26 && accessoryView != null) {
			keyboardHeight -= accessoryView.getBounds().getSize().getHeight();
			specialRightInset = accessoryView.getBounds().getSize().getHeight() + 3;
		}
		double leftInset = getView().getSafeAreaInsets().getLeft() > 0 ? getView().getSafeAreaInsets().getLeft() : fallbackInset;
		double rightInset = (getView().getSafeAreaInsets().getRight() > 0 ? getView().getSafeAreaInsets().getRight()
			: fallbackInset) + specialRightInset;
		newFrame.setOrigin(
			new CGPoint(leftInset, getView().getBounds().getSize().getHeight() - keyboardHeight - newFrame.getSize().getHeight()));
		newFrame.setSize(
			new CGSize(getView().getBounds().getSize().getWidth() - leftInset - rightInset, newFrame.getSize().getHeight()));
		textField.setFrame(newFrame);
		// The iOS 26+ toolbar (DefaultIOSInput.PinnedFrameToolbar) derives its real frame from the field on any geometry
		// write, so a dummy setFrame re-anchors it to the field's new position (and animates along inside an animation
		// block). For the plain pre-26 toolbar this is a no-op.
		if (accessoryView != null) accessoryView.setFrame(accessoryView.getFrame());
	}

	protected void moveTextFieldToBottom (boolean animated) {
		UIView textField = graphics.input.getActiveKeyboardTextField();
		if (textField == null || graphics.input.getNativeInputConfiguration() == null) return;
		// Synthetic keyboard frame: the bottom safe area, plus the accessory view that UIKit keeps showing at the bottom of
		// the screen while no on-screen keyboard is up (e.g. with a hardware keyboard)
		double height = getView().getSafeAreaInsets().getBottom();
		UIView accessoryView = textField.getInputAccessoryView();
		if (accessoryView != null) height += accessoryView.getBounds().getSize().getHeight();
		CGRect screenRect = UIScreen.getMainScreen().getBounds();
		CGRect keyboardFrameScreen = new CGRect(new CGPoint(0, screenRect.getSize().getHeight() - height),
			new CGSize(screenRect.getSize().getWidth(), height));
		if (animated) {
			UIView.animate(0.25, () -> layoutTextFieldAboveKeyboard(textField, keyboardFrameScreen));
		} else {
			layoutTextFieldAboveKeyboard(textField, keyboardFrameScreen);
		}
	}

	public void injectKeyboardNotification () {
		NSNotificationCenter.getDefaultCenter().addObserver(this, Selector.register("keyboardWillShow"),
			UIWindow.KeyboardWillShowNotification(), null);
		NSNotificationCenter.getDefaultCenter().addObserver(this, Selector.register("keyboardWillHide"),
			UIWindow.KeyboardWillHideNotification(), null);
	}

	@Override
	public void viewDidAppear (boolean animated) {
		super.viewDidAppear(animated);
		getView().setContentScaleFactor(UIScreen.getMainScreen().getNativeScale());
		if (app.viewControllerListener != null) app.viewControllerListener.viewDidAppear(animated);
	}

	@Override
	public UIInterfaceOrientationMask getSupportedInterfaceOrientations () {
		long mask = 0;
		if (app.config.orientationLandscape) {
			mask |= (1L << UIInterfaceOrientation.LandscapeLeft.value()) | (1L << UIInterfaceOrientation.LandscapeRight.value());
		}
		if (app.config.orientationPortrait) {
			mask |= 1L << UIInterfaceOrientation.Portrait.value();
			if (UIDevice.getCurrentDevice().getUserInterfaceIdiom() == UIUserInterfaceIdiom.Pad) {
				mask |= 1L << UIInterfaceOrientation.PortraitUpsideDown.value();
			}
		}
		return new UIInterfaceOrientationMask(mask);
	}

	@Override
	public boolean shouldAutorotate () {
		return true;
	}

	@Override
	public UIRectEdge getPreferredScreenEdgesDeferringSystemGestures () {
		return app.config.screenEdgesDeferringSystemGestures;
	}

	@Override
	public void viewDidLayoutSubviews () {
		super.viewDidLayoutSubviews();
		// get the view size and update graphics
		final IOSScreenBounds oldBounds = graphics.screenBounds;
		final IOSScreenBounds newBounds = app.computeBounds();
		graphics.screenBounds = newBounds;
		// Layout may happen without bounds changing, don't trigger resize in that case
		if (newBounds.width != oldBounds.width || newBounds.height != oldBounds.height) {
			graphics.makeCurrent();
			graphics.updateSafeInsets();
			graphics.gl20.glViewport(0, 0, newBounds.backBufferWidth, newBounds.backBufferHeight);
			if (graphics.config.hdpiMode == HdpiMode.Pixels) {
				app.listener.resize(newBounds.backBufferWidth, newBounds.backBufferHeight);
			} else {
				app.listener.resize(newBounds.width, newBounds.height);
			}
			// Rotating/resizing without an on-screen keyboard (hardware or floating keyboard) fires no keyboard
			// notification, so reposition the native input field here; with a docked keyboard keyboardWillShow re-fires
			// with the new keyboard frame and handles it instead
			if (!softKeyboardShown) moveTextFieldToBottom(false);
		}
	}

	@Override
	public boolean prefersStatusBarHidden () {
		return !app.config.statusBarVisible;
	}

	@Override
	public boolean prefersHomeIndicatorAutoHidden () {
		return app.config.hideHomeIndicator;
	}

	@Override
	public void pressesBegan (NSSet<UIPress> presses, UIPressesEvent event) {
		if (presses == null || presses.isEmpty() || !app.input.onKey(presses.getValues().first().getKey(), true)) {
			super.pressesBegan(presses, event);
		}
	}

	@Override
	public void pressesEnded (NSSet<UIPress> presses, UIPressesEvent event) {
		if (presses == null || presses.isEmpty() || !app.input.onKey(presses.getValues().first().getKey(), false)) {
			super.pressesEnded(presses, event);
		}
	}
}
