/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.physics.bullet.linearmath.*;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class _btMprSupport_t extends BulletBase {
	private long swigCPtr;
	
	protected _btMprSupport_t(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, cPtr, cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	/** Construct a new _btMprSupport_t, normally you should not need this constructor it's intended for low-level usage. */ 
	public _btMprSupport_t(long cPtr, boolean cMemoryOwn) {
		this("_btMprSupport_t", cPtr, cMemoryOwn);
		construct();
	}
	
	@Override
	protected void reset(long cPtr, boolean cMemoryOwn) {
		if (!destroyed)
			destroy();
		super.reset(swigCPtr = cPtr, cMemoryOwn);
	}
	
	public static long getCPtr(_btMprSupport_t obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CollisionJNI.delete__btMprSupport_t(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public void setV(btVector3 value) {
    CollisionJNI._btMprSupport_t_v_set(swigCPtr, this, btVector3.getCPtr(value), value);
  }

  public btVector3 getV() {
    long cPtr = CollisionJNI._btMprSupport_t_v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3(cPtr, false);
  }

  public void setV1(btVector3 value) {
    CollisionJNI._btMprSupport_t_v1_set(swigCPtr, this, btVector3.getCPtr(value), value);
  }

  public btVector3 getV1() {
    long cPtr = CollisionJNI._btMprSupport_t_v1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3(cPtr, false);
  }

  public void setV2(btVector3 value) {
    CollisionJNI._btMprSupport_t_v2_set(swigCPtr, this, btVector3.getCPtr(value), value);
  }

  public btVector3 getV2() {
    long cPtr = CollisionJNI._btMprSupport_t_v2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3(cPtr, false);
  }

  public _btMprSupport_t() {
    this(CollisionJNI.new__btMprSupport_t(), true);
  }

}
