/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.physics.bullet.linearmath.*;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class btCapsuleShape extends btConvexInternalShape {
	private long swigCPtr;
	
	protected btCapsuleShape(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, CollisionJNI.btCapsuleShape_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	/** Construct a new btCapsuleShape, normally you should not need this constructor it's intended for low-level usage. */
	public btCapsuleShape(long cPtr, boolean cMemoryOwn) {
		this("btCapsuleShape", cPtr, cMemoryOwn);
		construct();
	}
	
	@Override
	protected void reset(long cPtr, boolean cMemoryOwn) {
		if (!destroyed)
			destroy();
		super.reset(CollisionJNI.btCapsuleShape_SWIGUpcast(swigCPtr = cPtr), cMemoryOwn);
	}
	
	public static long getCPtr(btCapsuleShape obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CollisionJNI.delete_btCapsuleShape(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public btCapsuleShape(float radius, float height) {
    this(CollisionJNI.new_btCapsuleShape__SWIG_1(radius, height), true);
  }

  public int getUpAxis() {
    return CollisionJNI.btCapsuleShape_getUpAxis(swigCPtr, this);
  }

  public float getRadius() {
    return CollisionJNI.btCapsuleShape_getRadius(swigCPtr, this);
  }

  public float getHalfHeight() {
    return CollisionJNI.btCapsuleShape_getHalfHeight(swigCPtr, this);
  }

  public void deSerializeFloat(btCapsuleShapeData dataBuffer) {
    CollisionJNI.btCapsuleShape_deSerializeFloat(swigCPtr, this, btCapsuleShapeData.getCPtr(dataBuffer), dataBuffer);
  }

}
