/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.physics.bullet.linearmath.*;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class btConeShape extends btConvexInternalShape {
	private long swigCPtr;
	
	protected btConeShape(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, CollisionJNI.btConeShape_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	/** Construct a new btConeShape, normally you should not need this constructor it's intended for low-level usage. */
	public btConeShape(long cPtr, boolean cMemoryOwn) {
		this("btConeShape", cPtr, cMemoryOwn);
		construct();
	}
	
	@Override
	protected void reset(long cPtr, boolean cMemoryOwn) {
		if (!destroyed)
			destroy();
		super.reset(CollisionJNI.btConeShape_SWIGUpcast(swigCPtr = cPtr), cMemoryOwn);
	}
	
	public static long getCPtr(btConeShape obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CollisionJNI.delete_btConeShape(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public btConeShape(float radius, float height) {
    this(CollisionJNI.new_btConeShape(radius, height), true);
  }

  public float getRadius() {
    return CollisionJNI.btConeShape_getRadius(swigCPtr, this);
  }

  public float getHeight() {
    return CollisionJNI.btConeShape_getHeight(swigCPtr, this);
  }

  public void setConeUpIndex(int upIndex) {
    CollisionJNI.btConeShape_setConeUpIndex(swigCPtr, this, upIndex);
  }

  public int getConeUpIndex() {
    return CollisionJNI.btConeShape_getConeUpIndex(swigCPtr, this);
  }

}
