/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

import com.badlogic.gdx.utils.SharedLibraryLoader;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;

public class btBroadphaseRayCallback extends btBroadphaseAabbCallback {
  private long swigCPtr;

  public btBroadphaseRayCallback(long cPtr, boolean cMemoryOwn) {
    super(gdxBulletJNI.btBroadphaseRayCallback_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(btBroadphaseRayCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gdxBulletJNI.delete_btBroadphaseRayCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  static {
    new SharedLibraryLoader().load("gdx-bullet");
  }

  public void setM_rayDirectionInverse(btVector3 value) {
    gdxBulletJNI.btBroadphaseRayCallback_m_rayDirectionInverse_set(swigCPtr, this, btVector3.getCPtr(value), value);
  }

  public btVector3 getM_rayDirectionInverse() {
    long cPtr = gdxBulletJNI.btBroadphaseRayCallback_m_rayDirectionInverse_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3(cPtr, false);
  }

  public void setM_signs(long[] value) {
    gdxBulletJNI.btBroadphaseRayCallback_m_signs_set(swigCPtr, this, value);
  }

  public long[] getM_signs() {
    return gdxBulletJNI.btBroadphaseRayCallback_m_signs_get(swigCPtr, this);
  }

  public void setM_lambda_max(float value) {
    gdxBulletJNI.btBroadphaseRayCallback_m_lambda_max_set(swigCPtr, this, value);
  }

  public float getM_lambda_max() {
    return gdxBulletJNI.btBroadphaseRayCallback_m_lambda_max_get(swigCPtr, this);
  }

}
