/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

import com.badlogic.gdx.utils.SharedLibraryLoader;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;

public class btCollisionAlgorithmConstructionInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected btCollisionAlgorithmConstructionInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(btCollisionAlgorithmConstructionInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gdxBulletJNI.delete_btCollisionAlgorithmConstructionInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static {
    new SharedLibraryLoader().load("gdx-bullet");
  }

  public btCollisionAlgorithmConstructionInfo() {
    this(gdxBulletJNI.new_btCollisionAlgorithmConstructionInfo__SWIG_0(), true);
  }

  public btCollisionAlgorithmConstructionInfo(btDispatcher dispatcher, int temp) {
    this(gdxBulletJNI.new_btCollisionAlgorithmConstructionInfo__SWIG_1(btDispatcher.getCPtr(dispatcher), dispatcher, temp), true);
  }

  public void setM_dispatcher1(btDispatcher value) {
    gdxBulletJNI.btCollisionAlgorithmConstructionInfo_m_dispatcher1_set(swigCPtr, this, btDispatcher.getCPtr(value), value);
  }

  public btDispatcher getM_dispatcher1() {
    long cPtr = gdxBulletJNI.btCollisionAlgorithmConstructionInfo_m_dispatcher1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btDispatcher(cPtr, false);
  }

  public void setM_manifold(btPersistentManifold value) {
    gdxBulletJNI.btCollisionAlgorithmConstructionInfo_m_manifold_set(swigCPtr, this, btPersistentManifold.getCPtr(value), value);
  }

  public btPersistentManifold getM_manifold() {
    long cPtr = gdxBulletJNI.btCollisionAlgorithmConstructionInfo_m_manifold_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btPersistentManifold(cPtr, false);
  }

}
