/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class btCollisionObjectWrapper extends BulletBase {
	private long swigCPtr;
	
	protected btCollisionObjectWrapper(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, cPtr, cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected btCollisionObjectWrapper(long cPtr, boolean cMemoryOwn) {
		this("btCollisionObjectWrapper", cPtr, cMemoryOwn);
		construct();
	}
	
	public static long getCPtr(btCollisionObjectWrapper obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				throw new UnsupportedOperationException("C++ destructor does not have public access");
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	/** Temporary instance, use by native methods that return a btCollisionObjectWrapper instance */
	protected final static btCollisionObjectWrapper temp = new btCollisionObjectWrapper(0, false);
	public static btCollisionObjectWrapper internalTemp(long cPtr, boolean own) {
		temp.reset(cPtr, own);
		return temp;
	}
	/** Pool of btCollisionObjectWrapper instances, used by director interface to provide the arguments. */
	protected static final com.badlogic.gdx.utils.Pool<btCollisionObjectWrapper> pool = new com.badlogic.gdx.utils.Pool<btCollisionObjectWrapper>() {
		@Override
		protected btCollisionObjectWrapper newObject() {
			return new btCollisionObjectWrapper(0, false);
		}
	};
	/** Reuses a previous freed instance or creates a new instance and set it to reflect the specified native object */
	public static btCollisionObjectWrapper obtain(long cPtr, boolean own) {
		final btCollisionObjectWrapper result = pool.obtain();
		result.reset(cPtr, own);
		return result;
	}
	/** delete the native object if required and allow the instance to be reused by the obtain method */
	public static void free(final btCollisionObjectWrapper inst) {
		inst.dispose();
		pool.free(inst);
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  public void setParent(btCollisionObjectWrapper value) {
    gdxBulletJNI.btCollisionObjectWrapper_parent_set(swigCPtr, this, btCollisionObjectWrapper.getCPtr(value), value);
  }

  public btCollisionObjectWrapper getParent() {
	return btCollisionObjectWrapper.internalTemp(gdxBulletJNI.btCollisionObjectWrapper_parent_get(swigCPtr, this), false);
}

  public void setShape(btCollisionShape value) {
    gdxBulletJNI.btCollisionObjectWrapper_shape_set(swigCPtr, this, btCollisionShape.getCPtr(value), value);
  }

  public btCollisionShape getShape() {
    long cPtr = gdxBulletJNI.btCollisionObjectWrapper_shape_get(swigCPtr, this);
    return (cPtr == 0) ? null : btCollisionShape.newDerivedObject(cPtr, false);
  }

  public void setCollisionObject(btCollisionObject value) {
    gdxBulletJNI.btCollisionObjectWrapper_collisionObject_set(swigCPtr, this, btCollisionObject.getCPtr(value), value);
  }

  public btCollisionObject getCollisionObject() {
	return btCollisionObject.getInstance(gdxBulletJNI.btCollisionObjectWrapper_collisionObject_get(swigCPtr, this), false);
}

  public Matrix4 getWorldTransform() {
	return gdxBulletJNI.btCollisionObjectWrapper_worldTransform_get(swigCPtr, this);
}

  public btCollisionShape getCollisionShape() {
    long cPtr = gdxBulletJNI.btCollisionObjectWrapper_getCollisionShape(swigCPtr, this);
    return (cPtr == 0) ? null : btCollisionShape.newDerivedObject(cPtr, false);
  }

}
