/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

import com.badlogic.gdx.utils.SharedLibraryLoader;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;

public class btGeneric6DofConstraintData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected btGeneric6DofConstraintData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(btGeneric6DofConstraintData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gdxBulletJNI.delete_btGeneric6DofConstraintData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static {
    new SharedLibraryLoader().load("gdx-bullet");
  }

  public void setM_typeConstraintData(btTypedConstraintData value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_typeConstraintData_set(swigCPtr, this, btTypedConstraintData.getCPtr(value), value);
  }

  public btTypedConstraintData getM_typeConstraintData() {
    long cPtr = gdxBulletJNI.btGeneric6DofConstraintData_m_typeConstraintData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btTypedConstraintData(cPtr, false);
  }

  public void setM_rbAFrame(btTransformFloatData value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_rbAFrame_set(swigCPtr, this, btTransformFloatData.getCPtr(value), value);
  }

  public btTransformFloatData getM_rbAFrame() {
    long cPtr = gdxBulletJNI.btGeneric6DofConstraintData_m_rbAFrame_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btTransformFloatData(cPtr, false);
  }

  public void setM_rbBFrame(btTransformFloatData value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_rbBFrame_set(swigCPtr, this, btTransformFloatData.getCPtr(value), value);
  }

  public btTransformFloatData getM_rbBFrame() {
    long cPtr = gdxBulletJNI.btGeneric6DofConstraintData_m_rbBFrame_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btTransformFloatData(cPtr, false);
  }

  public void setM_linearUpperLimit(btVector3FloatData value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_linearUpperLimit_set(swigCPtr, this, btVector3FloatData.getCPtr(value), value);
  }

  public btVector3FloatData getM_linearUpperLimit() {
    long cPtr = gdxBulletJNI.btGeneric6DofConstraintData_m_linearUpperLimit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3FloatData(cPtr, false);
  }

  public void setM_linearLowerLimit(btVector3FloatData value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_linearLowerLimit_set(swigCPtr, this, btVector3FloatData.getCPtr(value), value);
  }

  public btVector3FloatData getM_linearLowerLimit() {
    long cPtr = gdxBulletJNI.btGeneric6DofConstraintData_m_linearLowerLimit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3FloatData(cPtr, false);
  }

  public void setM_angularUpperLimit(btVector3FloatData value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_angularUpperLimit_set(swigCPtr, this, btVector3FloatData.getCPtr(value), value);
  }

  public btVector3FloatData getM_angularUpperLimit() {
    long cPtr = gdxBulletJNI.btGeneric6DofConstraintData_m_angularUpperLimit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3FloatData(cPtr, false);
  }

  public void setM_angularLowerLimit(btVector3FloatData value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_angularLowerLimit_set(swigCPtr, this, btVector3FloatData.getCPtr(value), value);
  }

  public btVector3FloatData getM_angularLowerLimit() {
    long cPtr = gdxBulletJNI.btGeneric6DofConstraintData_m_angularLowerLimit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3FloatData(cPtr, false);
  }

  public void setM_useLinearReferenceFrameA(int value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_useLinearReferenceFrameA_set(swigCPtr, this, value);
  }

  public int getM_useLinearReferenceFrameA() {
    return gdxBulletJNI.btGeneric6DofConstraintData_m_useLinearReferenceFrameA_get(swigCPtr, this);
  }

  public void setM_useOffsetForConstraintFrame(int value) {
    gdxBulletJNI.btGeneric6DofConstraintData_m_useOffsetForConstraintFrame_set(swigCPtr, this, value);
  }

  public int getM_useOffsetForConstraintFrame() {
    return gdxBulletJNI.btGeneric6DofConstraintData_m_useOffsetForConstraintFrame_get(swigCPtr, this);
  }

  public btGeneric6DofConstraintData() {
    this(gdxBulletJNI.new_btGeneric6DofConstraintData(), true);
  }

}
