/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class btMultiSphereShape extends btConvexInternalAabbCachingShape {
	private long swigCPtr;
	
	protected btMultiSphereShape(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, gdxBulletJNI.btMultiSphereShape_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected btMultiSphereShape(long cPtr, boolean cMemoryOwn) {
		this("btMultiSphereShape", cPtr, cMemoryOwn);
		construct();
	}
	
	public static long getCPtr(btMultiSphereShape obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				gdxBulletJNI.delete_btMultiSphereShape(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public btMultiSphereShape(Vector3[] positions, float[] radi, int numSpheres) {
    this(gdxBulletJNI.new_btMultiSphereShape(positions, radi, numSpheres), true);
  }

  public int getSphereCount() {
    return gdxBulletJNI.btMultiSphereShape_getSphereCount(swigCPtr, this);
  }

  public Vector3 getSpherePosition(int index) {
	return gdxBulletJNI.btMultiSphereShape_getSpherePosition(swigCPtr, this, index);
}

  public float getSphereRadius(int index) {
    return gdxBulletJNI.btMultiSphereShape_getSphereRadius(swigCPtr, this, index);
  }

}
