/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

public final class btRigidBodyFlags {
  public final static int BT_DISABLE_WORLD_GRAVITY = 1;
  public final static int BT_ENABLE_GYROPSCOPIC_FORCE = 2;
}

