/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class btVehicleTuning extends BulletBase {
	private long swigCPtr;
	
	protected btVehicleTuning(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, cPtr, cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected btVehicleTuning(long cPtr, boolean cMemoryOwn) {
		this("btVehicleTuning", cPtr, cMemoryOwn);
		construct();
	}
	
	public static long getCPtr(btVehicleTuning obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				gdxBulletJNI.delete_btVehicleTuning(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public btVehicleTuning() {
    this(gdxBulletJNI.new_btVehicleTuning(), true);
  }

  public void setSuspensionStiffness(float value) {
    gdxBulletJNI.btVehicleTuning_suspensionStiffness_set(swigCPtr, this, value);
  }

  public float getSuspensionStiffness() {
    return gdxBulletJNI.btVehicleTuning_suspensionStiffness_get(swigCPtr, this);
  }

  public void setSuspensionCompression(float value) {
    gdxBulletJNI.btVehicleTuning_suspensionCompression_set(swigCPtr, this, value);
  }

  public float getSuspensionCompression() {
    return gdxBulletJNI.btVehicleTuning_suspensionCompression_get(swigCPtr, this);
  }

  public void setSuspensionDamping(float value) {
    gdxBulletJNI.btVehicleTuning_suspensionDamping_set(swigCPtr, this, value);
  }

  public float getSuspensionDamping() {
    return gdxBulletJNI.btVehicleTuning_suspensionDamping_get(swigCPtr, this);
  }

  public void setMaxSuspensionTravelCm(float value) {
    gdxBulletJNI.btVehicleTuning_maxSuspensionTravelCm_set(swigCPtr, this, value);
  }

  public float getMaxSuspensionTravelCm() {
    return gdxBulletJNI.btVehicleTuning_maxSuspensionTravelCm_get(swigCPtr, this);
  }

  public void setFrictionSlip(float value) {
    gdxBulletJNI.btVehicleTuning_frictionSlip_set(swigCPtr, this, value);
  }

  public float getFrictionSlip() {
    return gdxBulletJNI.btVehicleTuning_frictionSlip_get(swigCPtr, this);
  }

  public void setMaxSuspensionForce(float value) {
    gdxBulletJNI.btVehicleTuning_maxSuspensionForce_set(swigCPtr, this, value);
  }

  public float getMaxSuspensionForce() {
    return gdxBulletJNI.btVehicleTuning_maxSuspensionForce_get(swigCPtr, this);
  }

}
