/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Matrix3;
import com.badlogic.gdx.math.Matrix4;

public class ContactDestroyedListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ContactDestroyedListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ContactDestroyedListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gdxBulletJNI.delete_ContactDestroyedListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    gdxBulletJNI.ContactDestroyedListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    gdxBulletJNI.ContactDestroyedListener_change_ownership(this, swigCPtr, true);
  }

  public ContactDestroyedListener() {
    this(gdxBulletJNI.new_ContactDestroyedListener(), true);
    gdxBulletJNI.ContactDestroyedListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void onContactDestroyed(int manifoldPointUserValue) {
    gdxBulletJNI.ContactDestroyedListener_onContactDestroyed(swigCPtr, this, manifoldPointUserValue);
  }

  public void enable() {
    gdxBulletJNI.ContactDestroyedListener_enable(swigCPtr, this);
  }

  public void disable() {
    gdxBulletJNI.ContactDestroyedListener_disable(swigCPtr, this);
  }

  public boolean isEnabled() {
    return gdxBulletJNI.ContactDestroyedListener_isEnabled(swigCPtr, this);
  }

}
