/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet;

public final class HullFlag {
  public final static int QF_TRIANGLES = (1 << 0);
  public final static int QF_REVERSE_ORDER = (1 << 1);
  public final static int QF_DEFAULT = QF_TRIANGLES;
}

